[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dipeo"
version = "1.0.0"
description = "DiPeO core library"
requires-python = ">=3.13"
dependencies = []  # Dependencies managed by root pyproject.toml

[tool.hatch.build.targets.wheel]
packages = ["."]
