"""
Auto-generated static node type for db.
DO NOT EDIT THIS FILE DIRECTLY.
Generated from: 
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, Literal

from dipeo.models.models import (
    NodeType, Vec2, NodeID, PersonID, MemoryConfig, MemorySettings, ToolConfig,
    HookTriggerMode, SupportedLanguage, HttpMethod, DBBlockSubType,
    NotionOperation, HookType, PersonLLMConfig, LLMService, ExtractPattern
)
from dipeo.core.static.generated_nodes import BaseExecutableNode


@dataclass(frozen=True)
class Node(BaseExecutableNode):
    """Database operations"""
    type: NodeType = field(default=NodeType.db, init=False)    file: Optional[str] = None    collection: Optional[str] = None    sub_type: Any    operation: str    query: Optional[str] = None    data: Optional[Dict[str, Any]] = None
    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()        data["file"] = self.file        data["collection"] = self.collection        data["sub_type"] = self.sub_type        data["operation"] = self.operation        data["query"] = self.query        data["data"] = self.data        return data