"""
Auto-generated static node type for endpoint.
DO NOT EDIT THIS FILE DIRECTLY.
Generated from: 
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, Literal

from dipeo.models.models import (
    NodeType, Vec2, NodeID, PersonID, MemoryConfig, MemorySettings, ToolConfig,
    HookTriggerMode, SupportedLanguage, HttpMethod, DBBlockSubType,
    NotionOperation, HookType, PersonLLMConfig, LLMService, ExtractPattern
)
from dipeo.core.static.generated_nodes import BaseExecutableNode


@dataclass(frozen=True)
class Node(BaseExecutableNode):
    """Exit point for diagram execution"""
    type: NodeType = field(default=NodeType.endpoint, init=False)    save_to_file: bool    file_name: Optional[str] = None
    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()        data["save_to_file"] = self.save_to_file        data["file_name"] = self.file_name        return data