"""
Auto-generated static node type for start.
DO NOT EDIT THIS FILE DIRECTLY.
Generated from: 
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, Literal

from dipeo.models.models import (
    NodeType, Vec2, NodeID, PersonID, MemoryConfig, MemorySettings, ToolConfig,
    HookTriggerMode, SupportedLanguage, HttpMethod, DBBlockSubType,
    NotionOperation, HookType, PersonLLMConfig, LLMService, ExtractPattern
)
from dipeo.core.static.generated_nodes import BaseExecutableNode


@dataclass(frozen=True)
class Node(BaseExecutableNode):
    """Entry point for diagram execution"""
    type: NodeType = field(default=NodeType.start, init=False)    custom_data: str    output_data_structure: Dict[str, Any]    trigger_mode: Optional[Any] = None    hook_event: Optional[str] = None    hook_filters: Optional[Dict[str, Any]] = None
    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()        data["custom_data"] = self.custom_data        data["output_data_structure"] = self.output_data_structure        data["trigger_mode"] = self.trigger_mode        data["hook_event"] = self.hook_event        data["hook_filters"] = self.hook_filters        return data