"""Domain ports for codegen infrastructure services."""

from typing import Any, Protocol

from .ir_builder_port import IRData


class IRCachePort(Protocol):
    async def get(self, key: str) -> IRData | None: ...

    async def set(self, key: str, data: IRData, ttl: int | None = None) -> None: ...

    async def invalidate(self, key: str) -> bool: ...

    async def clear_all(self) -> None: ...


class IRBuilderRegistryPort(Protocol):
    def register_builder(self, name: str, builder: Any) -> None: ...

    def get_builder(self, name: str) -> Any | None: ...

    def list_builders(self) -> list[str]: ...

    def has_builder(self, name: str) -> bool: ...


class TemplateRendererPort(Protocol):
    async def render(
        self, template_name: str, context: dict[str, Any], template_string: str | None = None
    ) -> str: ...

    def register_filter(self, name: str, filter_func: Any) -> None: ...

    def register_macro(self, name: str, macro_func: Any) -> None: ...

    def list_templates(self) -> list[str]: ...
