# Generate Field Configurations from Domain Models V2
# Simplified version using template_job for direct template rendering
# Generates UI field configurations from TypeScript interfaces

version: light

nodes:
  - label: Start
    type: start
    position: {x: 50, y: 300}
    props:
      custom_data:
        message: Starting field configurations generation with template job

  # Run batch parser if cache doesn't exist
  - label: Parse TypeScript Batch
    type: sub_diagram
    position: {x: 200, y: 300}
    props:
      diagram_name: codegen/diagrams/models/parse_all_typescript_batch
      diagram_format: light
      passInputData: false
      ignoreIfSub: true

  # Load all cached AST files at once
  - label: Load All AST Files
    type: db
    position: {x: 400, y: 300}
    props:
      operation: read
      sub_type: file
      source_details:
        - .temp/codegen_mappings_ast.json
        - .temp/diagram_ast.json
        - .temp/node_data_ast.json

  # Extract mappings
  - label: Extract Mappings
    type: code_job
    position: {x: 600, y: 150}
    props:
      language: python
      filePath: files/codegen/code/shared/extract_mappings.py
      functionName: main

  # Extract field configurations
  - label: Extract Field Configs
    type: code_job
    position: {x: 700, y: 300}
    props:
      language: python
      filePath: files/codegen/code/models/generate_field_configs/field_configs_generator.py
      functionName: extract_field_configs

  # Prepare template data
  - label: Prepare Template Data
    type: code_job
    position: {x: 900, y: 350}
    props:
      language: python
      filePath: files/codegen/code/models/generate_field_configs/field_configs_generator.py
      functionName: prepare_template_data
  
  # Use template_job for rendering - it now automatically unwraps default inputs
  - label: Render Field Configs Template
    type: template_job
    position: {x: 1100, y: 400}
    props:
      engine: jinja2
      template_path: files/codegen/templates/frontend/field_configs.j2
      output_path: apps/web/src/__generated__/fields.ts

  # Also write JSON output
  - label: Write Field Configs JSON
    type: code_job
    position: {x: 1100, y: 500}
    props:
      language: python
      filePath: files/codegen/code/shared/writers/json_writer.py
      functionName: main

  # Generate success summary
  - label: Generate Summary
    type: code_job
    position: {x: 1300, y: 450}
    props:
      language: python
      filePath: files/codegen/code/shared/generators/summary_generator.py
      functionName: main

  - label: End
    type: endpoint
    position: {x: 1500, y: 450}
    props:
      save_to_file: false

connections:
  # Run batch parser first
  - from: Start
    to: Parse TypeScript Batch
  
  # Load cached data after parsing
  - from: Parse TypeScript Batch
    to: Load All AST Files
  
  # Extract mappings from the loaded files
  - from: Load All AST Files
    to: Extract Mappings
    label: default
  
  # Pass all AST files to Extract Field Configs
  - from: Load All AST Files
    to: Extract Field Configs
    label: ast_files
  - from: Extract Mappings
    to: Extract Field Configs
    label: mappings
  
  # Prepare template data
  - from: Extract Field Configs
    to: Prepare Template Data
    label: node_configs
  
  # Pass prepared data directly to template - it now handles unwrapping automatically
  - from: Prepare Template Data
    to: Render Field Configs Template
  
  # Also write JSON output
  - from: Extract Field Configs
    to: Write Field Configs JSON
    label: node_configs
  
  # Generate summary
  - from: Extract Field Configs
    to: Generate Summary
    label: node_configs
  
  - from: Render Field Configs Template
    to: End
  - from: Write Field Configs JSON
    to: End
  - from: Generate Summary
    to: End