"""Generate nodes/index.ts file."""
import os
from pathlib import Path
from typing import Any, Dict, List, Tuple


def camel_to_snake(name: str) -> str:
    """Convert camelCase to snake_case."""
    result = []
    for i, char in enumerate(name):
        if char.isupper() and i > 0:
            # Add underscore before uppercase letter if previous char is lowercase
            if name[i-1].islower() or (i < len(name) - 1 and name[i+1].islower()):
                result.append('_')
        result.append(char.lower())
    return ''.join(result)


def get_spec_name_from_filename(filename: str) -> str:
    """Extract spec variable name from filename.
    e.g., 'person-job.spec.ts' -> 'personJobSpec'
    """
    base_name = filename.replace('.spec.ts', '')
    parts = base_name.split('-')
    # First part is lowercase, rest are capitalized
    camel_case = parts[0] + ''.join(part.capitalize() for part in parts[1:])
    return camel_case + 'Spec'


def get_registry_key_from_filename(filename: str) -> str:
    """Extract registry key from filename.
    e.g., 'person-job.spec.ts' -> 'person_job'
    """
    base_name = filename.replace('.spec.ts', '')
    return base_name.replace('-', '_')


def generate_node_specs_index(base_dir: Path) -> dict[str, Any]:
    """Generate the nodes/index.ts file - only exports individual specs, not the registry."""
    node_specs_dir = base_dir / 'dipeo' / 'models' / 'src' / 'nodes'
    output_path = node_specs_dir / 'index.ts'

    # Find all .spec.ts files
    spec_files = sorted([
        f.name for f in node_specs_dir.glob('*.spec.ts')
        if f.name not in ['index.ts', 'node-specifications.ts']
    ])

    if not spec_files:
        return {'error': 'No spec files found', 'output_path': str(output_path)}

    # Generate header
    lines = [
        "/**",
        " * Export all node specifications",
        " * Auto-generated by projects/codegen/code/models/generate_typescript_indexes.py",
        " */",
        ""
    ]

    # Generate exports (simple re-export pattern)
    for spec_file in spec_files:
        spec_name = get_spec_name_from_filename(spec_file)
        import_path = f"./{spec_file.replace('.ts', '.js')}"
        lines.append(f"export {{ {spec_name} }} from '{import_path}';")

    # Combine all parts
    content = '\n'.join(lines)

    # Write the file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return {
        'specs_output_path': str(output_path),
        'spec_count': len(spec_files),
        'spec_files': spec_files
    }


def main(inputs: dict[str, Any]) -> dict[str, Any]:
    """Generate TypeScript index file for node specs."""
    base_dir = Path(os.getenv('DIPEO_BASE_DIR', os.getcwd()))

    # Generate node specs index file
    results = generate_node_specs_index(base_dir)

    return results
