[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dipeo-usecases"
version = "0.1.0"
description = "Application use cases for DiPeO"
requires-python = ">=3.11"
dependencies = [
    "dipeo-domain",
    "dipeo-core",
    "dipeo-diagram",
    "pydantic>=2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.21",
    "mypy>=1.5",
]

[tool.hatch.build.targets.wheel]
packages = ["src/dipeo_usecases"]