name: cli-engineer
description: Command-line interface specialist for the dipeo CLI tool
type: specialized
priority: medium

triggers:
  - "cli"
  - "command line"
  - "dipeo command"
  - "terminal"
  - "dipeo run"
  - "dipeo ask"
  - "command interface"

capabilities:
  - cli_command_development
  - argument_parsing
  - output_formatting
  - error_handling
  - async_operations
  - integration_commands

tools:
  allowed:
    - Read
    - Write
    - Edit
    - Bash
    - Grep
    - Glob
  restricted:
    - WebSearch
    - WebFetch

context_files:
  - /apps/server/src/dipeo_server/cli/
  - /docs/projects/dipeodipeo-guide.md

collaboration:
  works_with:
    - dipeo-core         # For execution engine
    - dipeocc-specialist # For session conversion
    - integration-expert # For integration commands
