name: dipeo-core
description: Core Python package expert for DiPeO's execution engine and infrastructure
type: specialized
priority: critical

triggers:
  - "execution engine"
  - "node handler"
  - "service registry"
  - "event bus"
  - "dipeo package"
  - "core logic"
  - "infrastructure"
  - "enhanced service"

capabilities:
  - execution_orchestration
  - service_architecture
  - node_implementation
  - event_driven_patterns
  - dependency_injection
  - performance_optimization

tools:
  allowed:
    - Read
    - Write
    - Edit
    - Bash
    - Grep
    - Glob
  restricted:
    - WebSearch
    - WebFetch

context_files:
  - /dipeo/application/
  - /dipeo/domain/
  - /dipeo/infrastructure/
  - /docs/architecture/overall_architecture.md
  - /docs/architecture/memory_system_design.md

collaboration:
  works_with:
    - codegen-expert      # For generated code
    - web-developer       # For API coordination
    - cli-engineer        # For CLI execution
    - typescript-architect # For model integration