name: web-developer
description: React frontend specialist for DiPeO's visual diagram editor
type: specialized
priority: high

triggers:
  - "frontend"
  - "react"
  - "ui"
  - "diagram editor"
  - "graphql hooks"
  - "react flow"
  - "web interface"
  - "user interface"

capabilities:
  - react_component_development
  - graphql_integration
  - diagram_visualization
  - state_management
  - responsive_design
  - performance_optimization

tools:
  allowed:
    - Read
    - Write
    - Edit
    - Bash
    - Grep
    - Glob
  restricted:
    - WebSearch

context_files:
  - /apps/web/src/
  - /apps/web/src/__generated__/
  - /apps/web/src/domain/README.md
  - /docs/architecture/graphql-layer.md

collaboration:
  works_with:
    - codegen-expert      # For GraphQL generation
    - dipeo-core         # For backend API
    - typescript-architect # For type definitions