# Generate Field Configurations from Domain Models
# Replaces dipeo/models/scripts/generate-field-configs.ts
# Generates UI field configurations from TypeScript interfaces

version: light

nodes:
  - label: Start
    type: start
    position: {x: 50, y: 300}
    props:
      custom_data:
        message: Starting field configurations generation from cached AST data

  # Run batch parser if cache doesn't exist
  - label: Parse TypeScript Batch
    type: sub_diagram
    position: {x: 200, y: 300}
    props:
      diagram_name: codegen/diagrams/models/parse_all_typescript_batch
      diagram_format: light
      passInputData: false
      ignoreIfSub: true

  # Load cached codegen mappings AST
  - label: Load Mappings AST
    type: db
    position: {x: 400, y: 150}
    props:
      operation: read
      sub_type: file
      source_details: .temp/codegen_mappings_ast.json

  # Extract mappings
  - label: Extract Mappings
    type: code_job
    position: {x: 600, y: 150}
    props:
      language: python
      filePath: files/codegen/code/shared/extract_mappings.py
      functionName: main

  # Load cached diagram AST
  - label: Load Diagram AST
    type: db
    position: {x: 400, y: 300}
    props:
      operation: read
      sub_type: file
      source_details: .temp/diagram_ast.json

  # Load cached node data AST
  - label: Load Node Data AST
    type: db
    position: {x: 400, y: 400}
    props:
      operation: read
      sub_type: file
      source_details: .temp/node_data_ast.json

  # Extract field configurations
  - label: Extract Field Configs
    type: code_job
    position: {x: 700, y: 300}
    props:
      language: python
      filePath: files/codegen/code/models/extractors/field_config_extractor.py
      functionName: main

  # Load field configs template
  - label: Load Field Configs Template
    type: db
    position: {x: 700, y: 450}
    props:
      operation: read
      sub_type: file
      source_details: files/codegen/templates/models/field_configs.j2

  # Prepare template data
  - label: Prepare Template Data
    type: code_job
    position: {x: 900, y: 350}
    props:
      language: python
      filePath: files/codegen/code/generators/prepare_field_config_data.py
      functionName: prepare_field_config_data

  # Generate TypeScript field configs
  - label: Generate Field Configs Code
    type: code_job
    position: {x: 1100, y: 400}
    props:
      language: python
      filePath: files/codegen/code/generators/render_field_configs.py
      functionName: render_field_configs

  # Write TypeScript file
  - label: Write Field Configs TS
    type: db
    position: {x: 1300, y: 400}
    props:
      operation: write
      sub_type: file
      source_details: apps/web/src/__generated__/nodes/fields.ts

  # Also write JSON output
  - label: Write Field Configs JSON
    type: code_job
    position: {x: 1300, y: 500}
    props:
      language: python
      filePath: files/codegen/code/models/writers/json_writer.py
      functionName: main

  # Generate success summary
  - label: Generate Summary
    type: code_job
    position: {x: 1500, y: 450}
    props:
      language: python
      filePath: files/codegen/code/models/generators/summary_generator.py
      functionName: main

  - label: End
    type: endpoint
    position: {x: 1700, y: 450}
    props:
      save_to_file: false

connections:
  # Run batch parser first
  - from: Start
    to: Parse TypeScript Batch
  
  # Load cached data after parsing
  - from: Parse TypeScript Batch
    to: Load Mappings AST
  - from: Parse TypeScript Batch
    to: Load Diagram AST
  - from: Parse TypeScript Batch
    to: Load Node Data AST
  - from: Parse TypeScript Batch
    to: Load Field Configs Template
  
  # Extract mappings
  - from: Load Mappings AST
    to: Extract Mappings
    label: default
  
  # Extract field configs with cached data
  - from: Load Diagram AST
    to: Extract Field Configs
    label: default
  - from: Load Node Data AST
    to: Extract Field Configs
    label: node_data
  - from: Extract Mappings
    to: Extract Field Configs
    label: mappings
  
  # Prepare template data
  - from: Extract Field Configs
    to: Prepare Template Data
    label: node_configs
  
  # Generate TypeScript
  - from: Prepare Template Data
    to: Generate Field Configs Code
    label: default
  - from: Load Field Configs Template
    to: Generate Field Configs Code
    label: template_content
  
  # Write outputs
  - from: Generate Field Configs Code
    to: Write Field Configs TS
  - from: Extract Field Configs
    to: Write Field Configs JSON
    label: node_configs
  
  # Generate summary
  - from: Extract Field Configs
    to: Generate Summary
    label: node_configs
  - from: Write Field Configs TS
    to: End
  - from: Write Field Configs JSON
    to: End
  - from: Generate Summary
    to: End