import React, { Suspense, useCallback, useMemo, useState, useEffect, lazy } from 'react';
import { FixedSizeList as List } from 'react-window';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AdvancedDataListContainer, AdvancedDataListContainerProps } from './AdvancedDataList/Container';
import { Item as AdvancedItem } from './AdvancedDataList/Item';
import { useIntersectionObserver } from '../hooks/useIntersectionObserver';
import { useWebSocketClient } from '../hooks/useWebSocketClient';
import { sanitize } from '../utils/sanitize';
import { AdvancedDataListContextProvider } from '../context/AdvancedDataListContext';
import type { AdvancedDataListProps as CoreProps } from './types';