"""
Generated Strawberry GraphQL schema from TypeScript operation definitions.
DO NOT EDIT - Generated by DiPeO codegen

Generated at: 2025-10-03T18:53:34.477123
"""

import strawberry
from strawberry.types import Info
from strawberry.scalars import JSON
from strawberry.file_uploads import Upload
from typing import Any, Optional, Union
from collections.abc import AsyncGenerator
from datetime import datetime

# Import operation executor
from dipeo.application.graphql.operation_executor import OperationExecutor

# Import all operations
from dipeo.diagram_generated.graphql import operations

# Import input types and enums
from .inputs import *
from .enums import DiagramFormatGraphQL

# Import result types
from .results import (
    DiagramResult,
    DiagramListResult,
    NodeResult,
    NodeListResult,
    ExecutionResult,
    ExecutionListResult,
    PersonResult,
    PersonListResult,
    ApiKeyResult,
    ApiKeyListResult,
    ConversationResult,
    ConversationListResult,
    FileOperationResult,
    DeleteResult,
    TestResult,
    FormatConversionResult,
    ValidationResult,
    CliSessionResult,
    InteractiveResponseResult,
    BatchOperationResult,
)

# Import domain types for direct query returns
from .domain_types import (
    ExecutionStateType,
    DomainDiagramType,
    DomainPersonType,
    DomainApiKeyType,
    DomainNodeType,
    ExecutionUpdateType,  # For subscriptions
)


@strawberry.type
class Query:
    """Auto-generated Query type from TypeScript definitions"""


    # GraphQL field using noun form
    @strawberry.field(name="getApiKeys")
    async def get_api_keys_resolver(
        self,
        info: Info,
        service: Optional[str] = None
    ) -> JSON:
        """
        
        Operation: GetApiKeysOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        if service is not None:
            variables["service"] = service

        return await executor.execute("GetApiKeys", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getApiKey")
    async def get_api_key_resolver(
        self,
        info: Info,
        api_key_id: str
    ) -> DomainApiKeyType:
        """
        
        Operation: GetApiKeyOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["api_key_id"] = api_key_id

        return await executor.execute("GetApiKey", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getAvailableModels")
    async def get_available_models_resolver(
        self,
        info: Info,
        service: str,
        api_key_id: str
    ) -> JSON:
        """
        
        Operation: GetAvailableModelsOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["service"] = service
        variables["api_key_id"] = api_key_id

        return await executor.execute("GetAvailableModels", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="listConversations")
    async def list_conversations_resolver(
        self,
        info: Info,
        person_id: Optional[str] = None,
        execution_id: Optional[str] = None,
        search: Optional[str] = None,
        show_forgotten: Optional[bool] = None,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        since: Optional[str] = None
    ) -> list[JSON]:
        """
        
        Operation: ListConversationsOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        if person_id is not None:
            variables["person_id"] = person_id
        if execution_id is not None:
            variables["execution_id"] = execution_id
        if search is not None:
            variables["search"] = search
        if show_forgotten is not None:
            variables["show_forgotten"] = show_forgotten
        if limit is not None:
            variables["limit"] = limit
        if offset is not None:
            variables["offset"] = offset
        if since is not None:
            variables["since"] = since

        return await executor.execute("ListConversations", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getDiagram")
    async def get_diagram_resolver(
        self,
        info: Info,
        diagram_id: str
    ) -> DomainDiagramType:
        """
        
        Operation: GetDiagramOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["diagram_id"] = diagram_id

        return await executor.execute("GetDiagram", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="listDiagrams")
    async def list_diagrams_resolver(
        self,
        info: Info,
        filter: Optional[DiagramFilterInput] = None,
        limit: Optional[float] = None,
        offset: Optional[float] = None
    ) -> list[DomainDiagramType]:
        """
        
        Operation: ListDiagramsOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        if filter is not None:
            variables["filter"] = filter
        if limit is not None:
            variables["limit"] = limit
        if offset is not None:
            variables["offset"] = offset

        return await executor.execute("ListDiagrams", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getExecution")
    async def get_execution_resolver(
        self,
        info: Info,
        execution_id: str
    ) -> ExecutionStateType:
        """
        
        Operation: GetExecutionOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["execution_id"] = execution_id

        return await executor.execute("GetExecution", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="listExecutions")
    async def list_executions_resolver(
        self,
        info: Info,
        filter: Optional[ExecutionFilterInput] = None,
        limit: Optional[float] = None,
        offset: Optional[float] = None
    ) -> list[ExecutionStateType]:
        """
        
        Operation: ListExecutionsOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        if filter is not None:
            variables["filter"] = filter
        if limit is not None:
            variables["limit"] = limit
        if offset is not None:
            variables["offset"] = offset

        return await executor.execute("ListExecutions", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getSupportedFormats")
    async def get_supported_formats_resolver(
        self,
        info: Info
    ) -> JSON:
        """
        
        Operation: GetSupportedFormatsOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}

        return await executor.execute("GetSupportedFormats", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getPerson")
    async def get_person_resolver(
        self,
        info: Info,
        person_id: str
    ) -> DomainPersonType:
        """
        
        Operation: GetPersonOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["person_id"] = person_id

        return await executor.execute("GetPerson", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="listPersons")
    async def list_persons_resolver(
        self,
        info: Info,
        limit: Optional[float] = None
    ) -> list[DomainPersonType]:
        """
        
        Operation: ListPersonsOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        if limit is not None:
            variables["limit"] = limit

        return await executor.execute("ListPersons", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="listPromptFiles")
    async def list_prompt_files_resolver(
        self,
        info: Info
    ) -> list[JSON]:
        """
        
        Operation: ListPromptFilesOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}

        return await executor.execute("ListPromptFiles", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getPromptFile")
    async def get_prompt_file_resolver(
        self,
        info: Info,
        filename: str
    ) -> JSON:
        """
        
        Operation: GetPromptFileOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["filename"] = filename

        return await executor.execute("GetPromptFile", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getProviders")
    async def get_providers_resolver(
        self,
        info: Info
    ) -> JSON:
        """
        
        Operation: GetProvidersOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}

        return await executor.execute("GetProviders", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getProviderOperations")
    async def get_provider_operations_resolver(
        self,
        info: Info,
        provider: str
    ) -> JSON:
        """
        
        Operation: GetProviderOperationsOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["provider"] = provider

        return await executor.execute("GetProviderOperations", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getOperationSchema")
    async def get_operation_schema_resolver(
        self,
        info: Info,
        provider: str,
        operation: str
    ) -> JSON:
        """
        
        Operation: GetOperationSchemaOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["provider"] = provider
        variables["operation"] = operation

        return await executor.execute("GetOperationSchema", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getSystemInfo")
    async def get_system_info_resolver(
        self,
        info: Info
    ) -> JSON:
        """
        
        Operation: GetSystemInfoOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}

        return await executor.execute("GetSystemInfo", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getExecutionCapabilities")
    async def get_execution_capabilities_resolver(
        self,
        info: Info
    ) -> JSON:
        """
        
        Operation: GetExecutionCapabilitiesOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}

        return await executor.execute("GetExecutionCapabilities", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="healthCheck")
    async def health_check_resolver(
        self,
        info: Info
    ) -> JSON:
        """
        
        Operation: HealthCheckOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}

        return await executor.execute("HealthCheck", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getExecutionOrder")
    async def get_execution_order_resolver(
        self,
        info: Info,
        execution_id: str
    ) -> JSON:
        """
        
        Operation: GetExecutionOrderOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["execution_id"] = execution_id

        return await executor.execute("GetExecutionOrder", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getExecutionMetrics")
    async def get_execution_metrics_resolver(
        self,
        info: Info,
        execution_id: str
    ) -> JSON:
        """
        
        Operation: GetExecutionMetricsOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["execution_id"] = execution_id

        return await executor.execute("GetExecutionMetrics", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getExecutionHistory")
    async def get_execution_history_resolver(
        self,
        info: Info,
        diagram_id: Optional[str] = None,
        limit: Optional[float] = None,
        include_metrics: Optional[bool] = None
    ) -> JSON:
        """
        
        Operation: GetExecutionHistoryOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        if diagram_id is not None:
            variables["diagram_id"] = diagram_id
        if limit is not None:
            variables["limit"] = limit
        if include_metrics is not None:
            variables["include_metrics"] = include_metrics

        return await executor.execute("GetExecutionHistory", variables=variables)


    # GraphQL field using noun form
    @strawberry.field(name="getActiveCliSession")
    async def get_active_cli_session_resolver(
        self,
        info: Info
    ) -> JSON:
        """
        
        Operation: GetActiveCliSessionOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}

        return await executor.execute("GetActiveCliSession", variables=variables)





@strawberry.type
class Mutation:
    """Auto-generated Mutation type from TypeScript definitions"""


    @strawberry.field(name="createApiKey")
    async def create_api_key(
        self,
        info: Info,
        input: CreateApiKeyInput
    ) -> ApiKeyResult:
        """
        
        Operation: CreateApiKeyOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["input"] = input

        return await executor.execute("CreateApiKey", variables=variables)


    @strawberry.field(name="testApiKey")
    async def test_api_key(
        self,
        info: Info,
        api_key_id: str
    ) -> ApiKeyResult:
        """
        
        Operation: TestApiKeyOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["api_key_id"] = api_key_id

        return await executor.execute("TestApiKey", variables=variables)


    @strawberry.field(name="deleteApiKey")
    async def delete_api_key(
        self,
        info: Info,
        api_key_id: str
    ) -> DeleteResult:
        """
        
        Operation: DeleteApiKeyOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["api_key_id"] = api_key_id

        return await executor.execute("DeleteApiKey", variables=variables)


    @strawberry.field(name="registerCliSession")
    async def register_cli_session(
        self,
        info: Info,
        input: RegisterCliSessionInput
    ) -> CliSessionResult:
        """
        
        Operation: RegisterCliSessionOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["input"] = input

        return await executor.execute("RegisterCliSession", variables=variables)


    @strawberry.field(name="unregisterCliSession")
    async def unregister_cli_session(
        self,
        info: Info,
        input: UnregisterCliSessionInput
    ) -> CliSessionResult:
        """
        
        Operation: UnregisterCliSessionOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["input"] = input

        return await executor.execute("UnregisterCliSession", variables=variables)


    @strawberry.field(name="createDiagram")
    async def create_diagram(
        self,
        info: Info,
        input: CreateDiagramInput
    ) -> DiagramResult:
        """
        
        Operation: CreateDiagramOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["input"] = input

        return await executor.execute("CreateDiagram", variables=variables)


    @strawberry.field(name="executeDiagram")
    async def execute_diagram(
        self,
        info: Info,
        input: ExecuteDiagramInput
    ) -> ExecutionResult:
        """
        
        Operation: ExecuteDiagramOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["input"] = input

        return await executor.execute("ExecuteDiagram", variables=variables)


    @strawberry.field(name="deleteDiagram")
    async def delete_diagram(
        self,
        info: Info,
        diagram_id: str
    ) -> DeleteResult:
        """
        
        Operation: DeleteDiagramOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["diagram_id"] = diagram_id

        return await executor.execute("DeleteDiagram", variables=variables)


    @strawberry.field(name="controlExecution")
    async def control_execution(
        self,
        info: Info,
        input: ExecutionControlInput
    ) -> ExecutionResult:
        """
        
        Operation: ControlExecutionOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["input"] = input

        return await executor.execute("ControlExecution", variables=variables)


    @strawberry.field(name="sendInteractiveResponse")
    async def send_interactive_response(
        self,
        info: Info,
        input: InteractiveResponseInput
    ) -> ExecutionResult:
        """
        
        Operation: SendInteractiveResponseOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["input"] = input

        return await executor.execute("SendInteractiveResponse", variables=variables)


    @strawberry.field(name="updateNodeState")
    async def update_node_state(
        self,
        info: Info,
        input: UpdateNodeStateInput
    ) -> ExecutionResult:
        """
        
        Operation: UpdateNodeStateOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["input"] = input

        return await executor.execute("UpdateNodeState", variables=variables)


    @strawberry.field(name="uploadFile")
    async def upload_file(
        self,
        info: Info,
        file: Upload,
        path: Optional[str] = None
    ) -> JSON:
        """
        
        Operation: UploadFileOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["file"] = file
        if path is not None:
            variables["path"] = path

        return await executor.execute("UploadFile", variables=variables)


    @strawberry.field(name="uploadDiagram")
    async def upload_diagram(
        self,
        info: Info,
        file: Upload,
        format: DiagramFormatGraphQL
    ) -> JSON:
        """
        
        Operation: UploadDiagramOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["file"] = file
        variables["format"] = format

        return await executor.execute("UploadDiagram", variables=variables)


    @strawberry.field(name="validateDiagram")
    async def validate_diagram(
        self,
        info: Info,
        content: str,
        format: DiagramFormatGraphQL
    ) -> JSON:
        """
        
        Operation: ValidateDiagramOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["content"] = content
        variables["format"] = format

        return await executor.execute("ValidateDiagram", variables=variables)


    @strawberry.field(name="convertDiagramFormat")
    async def convert_diagram_format(
        self,
        info: Info,
        content: str,
        from_format: DiagramFormatGraphQL,
        to_format: DiagramFormatGraphQL
    ) -> FormatConversionResult:
        """
        
        Operation: ConvertDiagramFormatOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["content"] = content
        variables["from_format"] = from_format
        variables["to_format"] = to_format

        return await executor.execute("ConvertDiagramFormat", variables=variables)


    @strawberry.field(name="createNode")
    async def create_node(
        self,
        info: Info,
        diagram_id: str,
        input: CreateNodeInput
    ) -> NodeResult:
        """
        
        Operation: CreateNodeOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["diagram_id"] = diagram_id
        variables["input"] = input

        return await executor.execute("CreateNode", variables=variables)


    @strawberry.field(name="updateNode")
    async def update_node(
        self,
        info: Info,
        diagram_id: str,
        node_id: str,
        input: UpdateNodeInput
    ) -> NodeResult:
        """
        
        Operation: UpdateNodeOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["diagram_id"] = diagram_id
        variables["node_id"] = node_id
        variables["input"] = input

        return await executor.execute("UpdateNode", variables=variables)


    @strawberry.field(name="deleteNode")
    async def delete_node(
        self,
        info: Info,
        diagram_id: str,
        node_id: str
    ) -> DeleteResult:
        """
        
        Operation: DeleteNodeOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["diagram_id"] = diagram_id
        variables["node_id"] = node_id

        return await executor.execute("DeleteNode", variables=variables)


    @strawberry.field(name="createPerson")
    async def create_person(
        self,
        info: Info,
        input: CreatePersonInput
    ) -> PersonResult:
        """
        
        Operation: CreatePersonOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["input"] = input

        return await executor.execute("CreatePerson", variables=variables)


    @strawberry.field(name="updatePerson")
    async def update_person(
        self,
        info: Info,
        person_id: str,
        input: UpdatePersonInput
    ) -> PersonResult:
        """
        
        Operation: UpdatePersonOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["person_id"] = person_id
        variables["input"] = input

        return await executor.execute("UpdatePerson", variables=variables)


    @strawberry.field(name="deletePerson")
    async def delete_person(
        self,
        info: Info,
        person_id: str
    ) -> DeleteResult:
        """
        
        Operation: DeletePersonOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["person_id"] = person_id

        return await executor.execute("DeletePerson", variables=variables)





@strawberry.type
class Subscription:
    """Auto-generated Subscription type from TypeScript definitions"""


    @strawberry.subscription(name="executionUpdates")
    async def execution_updates(
        self,
        info: Info,
        execution_id: str
    ) -> AsyncGenerator[ExecutionUpdateType, None]:
        """
        
        Operation: ExecutionUpdatesOperation
        """
        from dipeo.application.graphql.operation_executor import OperationExecutor
        executor = OperationExecutor(info.context.service_registry)

        # Build variables dict from typed parameters
        variables = {}
        variables["execution_id"] = execution_id

        # Execute subscription and yield items
        async for item in executor.execute_subscription("ExecutionUpdates", variables=variables):
            yield item




# Export the schema types
__all__ = [
    'Query',
    'Mutation',
    'Subscription',
]
