"""
Auto-generated static node types from domain models.
DO NOT EDIT THIS FILE DIRECTLY.
Generated at: 2025-07-25T22:50:58.681338
Generated by: domain model static nodes generation
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, Literal

from dipeo.models.models import (
    NodeType, Vec2, NodeID, PersonID, MemoryConfig, MemorySettings, ToolConfig,
    HookTriggerMode, SupportedLanguage, HttpMethod, DBBlockSubType,
    NotionOperation, HookType, PersonLLMConfig, LLMService, DiagramFormat
)


@dataclass(frozen=True)
class BaseExecutableNode:
    """Base class for all executable node types."""
    id: NodeID
    type: NodeType
    position: Vec2
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        result = {
            "id": self.id,
            "type": self.type.value,
            "position": {"x": self.position.x, "y": self.position.y},
            "label": self.label,
            "flipped": self.flipped
        }
        if self.metadata:
            result["metadata"] = self.metadata
        return result


@dataclass(frozen=True)
class StartNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.start, init=False)
    custom_data: Dict[str, Any] = field(default_factory=dict)
    output_data_structure: Dict[str, str] = field(default_factory=dict)
    trigger_mode: Optional[HookTriggerMode] = None
    hook_event: str = None
    hook_filters: Any = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["custom_data"] = self.custom_data
        data["output_data_structure"] = self.output_data_structure
        data["trigger_mode"] = self.trigger_mode
        data["hook_event"] = self.hook_event
        data["hook_filters"] = self.hook_filters
        return data


@dataclass(frozen=True)
class PersonJobNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.person_job, init=False)
    person_id: Optional[PersonID] = None
    first_only_prompt: str = ""
    default_prompt: str = None
    max_iteration: int = 1
    memory_config: Optional[MemoryConfig] = None
    memory_settings: Optional[MemorySettings] = None
    tools: Optional[{}] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["person"] = self.person_id
        data["first_only_prompt"] = self.first_only_prompt
        data["default_prompt"] = self.default_prompt
        data["max_iteration"] = self.max_iteration
        data["memory_config"] = self.memory_config
        data["memory_settings"] = self.memory_settings
        data["tools"] = self.tools
        return data


@dataclass(frozen=True)
class ConditionNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.condition, init=False)
    condition_type: str = ""
    expression: str = None
    node_indices: Optional[{}] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["condition_type"] = self.condition_type
        data["expression"] = self.expression
        data["node_indices"] = self.node_indices
        return data


@dataclass(frozen=True)
class EndpointNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.endpoint, init=False)
    save_to_file: bool = False
    file_name: str = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["save_to_file"] = self.save_to_file
        data["file_name"] = self.file_name
        return data


@dataclass(frozen=True)
class DBNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.db, init=False)
    file: str = None
    collection: str = None
    sub_type: DBBlockSubType = DBBlockSubType.fixed_prompt
    operation: str = ""
    query: str = None
    data: Any = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["file"] = self.file
        data["collection"] = self.collection
        data["sub_type"] = self.sub_type
        data["operation"] = self.operation
        data["query"] = self.query
        data["data"] = self.data
        return data


@dataclass(frozen=True)
class CodeJobNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.code_job, init=False)
    language: SupportedLanguage = SupportedLanguage.python
    filePath: str = None
    code: str = None
    functionName: str = None
    timeout: int = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["language"] = self.language
        data["filePath"] = self.filePath
        data["code"] = self.code
        data["functionName"] = self.functionName
        data["timeout"] = self.timeout
        return data


@dataclass(frozen=True)
class ApiJobNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.api_job, init=False)
    url: str = ""
    method: HttpMethod = HttpMethod.GET
    headers: Any = None
    params: Any = None
    body: Any = None
    timeout: int = None
    auth_type: Optional[Literal["none", "bearer", "basic", "api_key"]] = None
    auth_config: Any = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["url"] = self.url
        data["method"] = self.method
        data["headers"] = self.headers
        data["params"] = self.params
        data["body"] = self.body
        data["timeout"] = self.timeout
        data["auth_type"] = self.auth_type
        data["auth_config"] = self.auth_config
        return data


@dataclass(frozen=True)
class UserResponseNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.user_response, init=False)
    prompt: str = ""
    timeout: int = 60

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["prompt"] = self.prompt
        data["timeout"] = self.timeout
        return data


@dataclass(frozen=True)
class NotionNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.notion, init=False)
    operation: NotionOperation = NotionOperation.read_page
    page_id: str = None
    database_id: str = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["operation"] = self.operation
        data["page_id"] = self.page_id
        data["database_id"] = self.database_id
        return data


@dataclass(frozen=True)
class HookNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.hook, init=False)
    hook_type: HookType = HookType.shell
    config: Literal["{ command?: string; args?: {}; env?: any; cwd?: string; url?: string; method?: HttpMethod; headers?: any; script?: string; function_name?: string; file_path?: string; format?: json", "yaml", "text; }"] = field(default_factory=dict)
    timeout: int = None
    retry_count: int = None
    retry_delay: int = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["hook_type"] = self.hook_type
        data["config"] = self.config
        data["timeout"] = self.timeout
        data["retry_count"] = self.retry_count
        data["retry_delay"] = self.retry_delay
        return data


@dataclass(frozen=True)
class TemplateJobNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.template_job, init=False)
    template_path: str = None
    template_content: str = None
    output_path: str = None
    variables: Any = None
    engine: Optional[Literal["internal", "jinja2", "handlebars"]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["template_path"] = self.template_path
        data["template_content"] = self.template_content
        data["output_path"] = self.output_path
        data["variables"] = self.variables
        data["engine"] = self.engine
        return data


@dataclass(frozen=True)
class JsonSchemaValidatorNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.json_schema_validator, init=False)
    schema_path: str = None
    schema: Any = None
    data_path: str = None
    strict_mode: bool = False
    error_on_extra: bool = False

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["schema_path"] = self.schema_path
        data["schema"] = self.schema
        data["data_path"] = self.data_path
        data["strict_mode"] = self.strict_mode
        data["error_on_extra"] = self.error_on_extra
        return data


@dataclass(frozen=True)
class TypescriptAstNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.typescript_ast, init=False)
    source: str = None
    extractPatterns: Optional[{}] = field(default_factory=lambda: ["interface", "type", "enum"])
    includeJSDoc: bool = False
    parseMode: Optional[Literal["module", "script"]] = "module"

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["source"] = self.source
        data["extractPatterns"] = self.extractPatterns
        data["includeJSDoc"] = self.includeJSDoc
        data["parseMode"] = self.parseMode
        return data


@dataclass(frozen=True)
class SubDiagramNode(BaseExecutableNode):
    type: NodeType = field(default=NodeType.sub_diagram, init=False)
    diagram_name: str = None
    diagram_format: DiagramFormat = None
    diagram_data: Any = None
    batch: bool = False
    batch_input_key: str = "items"
    batch_parallel: bool = True

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["diagram_name"] = self.diagram_name
        data["diagram_format"] = self.diagram_format
        data["diagram_data"] = self.diagram_data
        data["batch"] = self.batch
        data["batch_input_key"] = self.batch_input_key
        data["batch_parallel"] = self.batch_parallel
        return data


@dataclass(frozen=True)
class PersonBatchJobNode(PersonJobNode):
    """Person batch job node - same as PersonJobNode but with different type."""
    type: NodeType = field(default=NodeType.person_batch_job, init=False)


ExecutableNode = Union[
    StartNode,
    PersonJobNode,
    ConditionNode,
    EndpointNode,
    DBNode,
    CodeJobNode,
    ApiJobNode,
    UserResponseNode,
    NotionNode,
    HookNode,
    TemplateJobNode,
    JsonSchemaValidatorNode,
    TypescriptAstNode,
    SubDiagramNode
]


def create_executable_node(
    node_type: NodeType,
    node_id: NodeID,
    position: Vec2,
    label: str = "",
    data: Optional[Dict[str, Any]] = None,
    flipped: bool = False,
    metadata: Optional[Dict[str, Any]] = None
) -> ExecutableNode:
    """Factory function to create typed executable nodes from diagram data."""
    data = data or {}
    
    if node_type == NodeType.start:
        return StartNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            custom_data=data.get("custom_data"),
            output_data_structure=data.get("output_data_structure"),
            trigger_mode=data.get("trigger_mode", None),
            hook_event=data.get("hook_event", None),
            hook_filters=data.get("hook_filters", None),
        )
    
    if node_type == NodeType.person_job:
        return PersonJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            person_id=data.get("person", None),
            first_only_prompt=data.get("first_only_prompt", ""),
            default_prompt=data.get("default_prompt", None),
            max_iteration=data.get("max_iteration", 1),
            memory_config=MemoryConfig(**data.get("memory_config")) if data.get("memory_config") else None,
            memory_settings=MemorySettings(**data.get("memory_settings")) if data.get("memory_settings") else None,
            tools=[ToolConfig(**tool) if isinstance(tool, dict) else tool for tool in data.get("tools", [])] if data.get("tools") else None,
        )
    
    if node_type == NodeType.condition:
        return ConditionNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            condition_type=data.get("condition_type", ""),
            expression=data.get("expression", None),
            node_indices=data.get("node_indices", None),
        )
    
    if node_type == NodeType.endpoint:
        return EndpointNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            save_to_file=data.get("save_to_file", False),
            file_name=data.get("file_name", None),
        )
    
    if node_type == NodeType.db:
        return DBNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            file=data.get("file", None),
            collection=data.get("collection", None),
            sub_type=data.get("sub_type", DBBlockSubType.fixed_prompt),
            operation=data.get("operation", ""),
            query=data.get("query", None),
            data=data.get("data", None),
        )
    
    if node_type == NodeType.code_job:
        return CodeJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            language=data.get("language", SupportedLanguage.python),
            filePath=data.get("filePath", None),
            code=data.get("code", None),
            functionName=data.get("functionName", None),
            timeout=data.get("timeout", None),
        )
    
    if node_type == NodeType.api_job:
        return ApiJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            url=data.get("url", ""),
            method=data.get("method", HttpMethod.GET),
            headers=data.get("headers", None),
            params=data.get("params", None),
            body=data.get("body", None),
            timeout=data.get("timeout", None),
            auth_type=data.get("auth_type", None),
            auth_config=data.get("auth_config", None),
        )
    
    if node_type == NodeType.user_response:
        return UserResponseNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            prompt=data.get("prompt", ""),
            timeout=data.get("timeout", 60),
        )
    
    if node_type == NodeType.notion:
        return NotionNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            operation=data.get("operation", NotionOperation.read_page),
            page_id=data.get("page_id", None),
            database_id=data.get("database_id", None),
        )
    
    if node_type == NodeType.hook:
        return HookNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            hook_type=data.get("hook_type", HookType.shell),
            config=data.get("config"),
            timeout=data.get("timeout", None),
            retry_count=data.get("retry_count", None),
            retry_delay=data.get("retry_delay", None),
        )
    
    if node_type == NodeType.template_job:
        return TemplateJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            template_path=data.get("template_path", None),
            template_content=data.get("template_content", None),
            output_path=data.get("output_path", None),
            variables=data.get("variables", None),
            engine=data.get("engine", None),
        )
    
    if node_type == NodeType.json_schema_validator:
        return JsonSchemaValidatorNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            schema_path=data.get("schema_path", None),
            schema=data.get("schema", None),
            data_path=data.get("data_path", None),
            strict_mode=data.get("strict_mode", False),
            error_on_extra=data.get("error_on_extra", False),
        )
    
    if node_type == NodeType.typescript_ast:
        return TypescriptAstNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            source=data.get("source", None),
            extractPatterns=data.get("extractPatterns"),
            includeJSDoc=data.get("includeJSDoc", False),
            parseMode=data.get("parseMode", "module"),
        )
    
    if node_type == NodeType.sub_diagram:
        return SubDiagramNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            diagram_name=data.get("diagram_name", None),
            diagram_format=data.get("diagram_format", None),
            diagram_data=data.get("diagram_data", None),
            batch=data.get("batch", False),
            batch_input_key=data.get("batch_input_key", "items"),
            batch_parallel=data.get("batch_parallel", True),
        )
    
    if node_type == NodeType.person_batch_job:
        return PersonBatchJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            person_id=data.get("person"),
            first_only_prompt=data.get("first_only_prompt", ""),
            default_prompt=data.get("default_prompt"),
            max_iteration=data.get("max_iteration", 1),
            memory_config=MemoryConfig(**data.get("memory_config")) if data.get("memory_config") else None,
            memory_settings=MemorySettings(**data.get("memory_settings")) if data.get("memory_settings") else None,
            tools=[ToolConfig(**tool) if isinstance(tool, dict) else tool for tool in data.get("tools", [])] if data.get("tools") else None
        )
    
    raise ValueError(f"Unknown node type: {node_type}")