"""
Auto-generated static node types from domain models.
DO NOT EDIT THIS FILE DIRECTLY.
Generated at: 2025-08-21T13:57:20.140476
Generated by: domain model static nodes generation
"""


from dataclasses import *
from typing import *

from .domain_models import *
from .enums import *
from .integrations import *


def _to_enum(value: Optional[str], enum_class) -> Optional[Any]:
    """Convert string value to enum instance if not None."""
    if value is None:
        return None
    if isinstance(value, enum_class):
        return value
    return enum_class(value)


@dataclass(frozen=True)
class BaseExecutableNode:
    """Base class for all executable node types."""
    # Required fields only - no defaults in base class
    id: NodeID
    position: Vec2
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        result = {
            "id": self.id,
            "position": {"x": self.position.x, "y": self.position.y}
        }
        # Subclasses should extend this
        return result


# Debug: Show all available variables
# Available variables: now: 2025-08-21T13:57:20.140476
# static_nodes_data exists: yes
# static_nodes_data type: dict
# static_nodes_data keys: ['node_classes', 'enum_fields', 'now']
# Number of classes: 14

@dataclass(frozen=True)
class ApiJobNode(BaseExecutableNode):
    # Required node-specific fields
    url: str = field()
    method: HttpMethod = field()
    # Type field with default
    type: NodeType = field(default=NodeType.API_JOB, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    headers: Optional[Dict[str, str]] = None
    params: Optional[JsonDict] = None
    body: Optional[JsonValue] = None
    timeout: Optional[int] = None
    auth_type: Optional[AuthType] = None
    auth_config: Optional[Dict[str, str]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["url"] = self.url
        data["method"] = self.method
        data["headers"] = self.headers
        data["params"] = self.params
        data["body"] = self.body
        data["timeout"] = self.timeout
        data["auth_type"] = self.auth_type
        data["auth_config"] = self.auth_config
        return data



@dataclass(frozen=True)
class CodeJobNode(BaseExecutableNode):
    # Required node-specific fields
    language: SupportedLanguage = field()
    # Type field with default
    type: NodeType = field(default=NodeType.CODE_JOB, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    filePath: Optional[str] = None
    code: Optional[str] = None
    functionName: Optional[str] = None
    timeout: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["language"] = self.language
        data["filePath"] = self.filePath
        data["code"] = self.code
        data["functionName"] = self.functionName
        data["timeout"] = self.timeout
        return data



@dataclass(frozen=True)
class ConditionNode(BaseExecutableNode):
    # Type field with default
    type: NodeType = field(default=NodeType.CONDITION, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    condition_type: Optional[ConditionType] = None
    expression: Optional[str] = None
    node_indices: Optional[List[str]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["condition_type"] = self.condition_type
        data["expression"] = self.expression
        data["node_indices"] = self.node_indices
        return data



@dataclass(frozen=True)
class DBNode(BaseExecutableNode):
    # Required node-specific fields
    sub_type: DBBlockSubType = field()
    operation: str = field()
    # Type field with default
    type: NodeType = field(default=NodeType.DB, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    file: Optional[List[Union[str, str]]] = None
    collection: Optional[str] = None
    query: Optional[str] = None
    data: Optional[JsonDict] = None
    serialize_json: Optional[bool] = None
    glob: Optional[bool] = None
    format: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["file"] = self.file
        data["collection"] = self.collection
        data["sub_type"] = self.sub_type
        data["operation"] = self.operation
        data["query"] = self.query
        data["data"] = self.data
        data["serialize_json"] = self.serialize_json
        data["glob"] = self.glob
        data["format"] = self.format
        return data



@dataclass(frozen=True)
class EndpointNode(BaseExecutableNode):
    # Required node-specific fields
    save_to_file: bool = field()
    # Type field with default
    type: NodeType = field(default=NodeType.ENDPOINT, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    file_name: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["save_to_file"] = self.save_to_file
        data["file_name"] = self.file_name
        return data



@dataclass(frozen=True)
class HookNode(BaseExecutableNode):
    # Required node-specific fields
    hook_type: HookType = field()
    # Type field with default
    type: NodeType = field(default=NodeType.HOOK, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    command: Optional[str] = None
    args: Optional[List[str]] = None
    env: Optional[Dict[str, str]] = None
    cwd: Optional[str] = None
    url: Optional[str] = None
    method: Optional[HttpMethod] = None
    headers: Optional[Dict[str, str]] = None
    script: Optional[str] = None
    function_name: Optional[str] = None
    file_path: Optional[str] = None
    format: Optional[Literal["json", "yaml", "text"]] = None
    timeout: Optional[int] = None
    retry_count: Optional[int] = None
    retry_delay: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["hook_type"] = self.hook_type
        data["command"] = self.command
        data["args"] = self.args
        data["env"] = self.env
        data["cwd"] = self.cwd
        data["url"] = self.url
        data["method"] = self.method
        data["headers"] = self.headers
        data["script"] = self.script
        data["function_name"] = self.function_name
        data["file_path"] = self.file_path
        data["format"] = self.format
        data["timeout"] = self.timeout
        data["retry_count"] = self.retry_count
        data["retry_delay"] = self.retry_delay
        return data



@dataclass(frozen=True)
class IntegratedApiNode(BaseExecutableNode):
    # Required node-specific fields
    provider: str = field()
    operation: str = field()
    # Type field with default
    type: NodeType = field(default=NodeType.INTEGRATED_API, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    config: Optional[JsonDict] = None
    resource_id: Optional[str] = None
    timeout: Optional[int] = None
    max_retries: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["provider"] = self.provider
        data["operation"] = self.operation
        data["config"] = self.config
        data["resource_id"] = self.resource_id
        data["timeout"] = self.timeout
        data["max_retries"] = self.max_retries
        return data



@dataclass(frozen=True)
class JsonSchemaValidatorNode(BaseExecutableNode):
    # Type field with default
    type: NodeType = field(default=NodeType.JSON_SCHEMA_VALIDATOR, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    schema_path: Optional[str] = None
    json_schema: Optional[JsonDict] = None
    data_path: Optional[str] = None
    strict_mode: Optional[bool] = None
    error_on_extra: Optional[bool] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["schema_path"] = self.schema_path
        data["json_schema"] = self.json_schema
        data["data_path"] = self.data_path
        data["strict_mode"] = self.strict_mode
        data["error_on_extra"] = self.error_on_extra
        return data



@dataclass(frozen=True)
class PersonJobNode(BaseExecutableNode):
    # Required node-specific fields
    first_only_prompt: str = field()
    max_iteration: int = field()
    # Type field with default
    type: NodeType = field(default=NodeType.PERSON_JOB, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    person: Optional[PersonID] = None
    first_prompt_file: Optional[str] = None
    default_prompt: Optional[str] = None
    prompt_file: Optional[str] = None
    memory_profile: Optional[MemoryProfile] = None
    memory_settings: Optional[MemorySettings] = None
    tools: Optional[ToolSelection] = None
    text_format: Optional[str] = None
    text_format_file: Optional[str] = None
    batch: Optional[bool] = None
    batch_input_key: Optional[str] = None
    batch_parallel: Optional[bool] = None
    max_concurrent: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["person"] = self.person
        data["first_only_prompt"] = self.first_only_prompt
        data["first_prompt_file"] = self.first_prompt_file
        data["default_prompt"] = self.default_prompt
        data["prompt_file"] = self.prompt_file
        data["max_iteration"] = self.max_iteration
        data["memory_profile"] = self.memory_profile
        data["memory_settings"] = self.memory_settings
        data["tools"] = self.tools
        data["text_format"] = self.text_format
        data["text_format_file"] = self.text_format_file
        data["batch"] = self.batch
        data["batch_input_key"] = self.batch_input_key
        data["batch_parallel"] = self.batch_parallel
        data["max_concurrent"] = self.max_concurrent
        return data



@dataclass(frozen=True)
class StartNode(BaseExecutableNode):
    # Required node-specific fields
    trigger_mode: Optional[HookTriggerMode] = field()
    # Type field with default
    type: NodeType = field(default=NodeType.START, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    custom_data: Optional[Dict[str, Union[str, float, bool]]] = None
    output_data_structure: Optional[Dict[str, str]] = None
    hook_event: Optional[str] = None
    hook_filters: Optional[JsonDict] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["trigger_mode"] = self.trigger_mode
        data["custom_data"] = self.custom_data
        data["output_data_structure"] = self.output_data_structure
        data["hook_event"] = self.hook_event
        data["hook_filters"] = self.hook_filters
        return data



@dataclass(frozen=True)
class SubDiagramNode(BaseExecutableNode):
    # Type field with default
    type: NodeType = field(default=NodeType.SUB_DIAGRAM, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    diagram_name: Optional[str] = None
    diagram_format: Optional[DiagramFormat] = None
    diagram_data: Optional[JsonDict] = None
    batch: Optional[bool] = None
    batch_input_key: Optional[str] = None
    batch_parallel: Optional[bool] = None
    ignoreIfSub: Optional[bool] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["diagram_name"] = self.diagram_name
        data["diagram_format"] = self.diagram_format
        data["diagram_data"] = self.diagram_data
        data["batch"] = self.batch
        data["batch_input_key"] = self.batch_input_key
        data["batch_parallel"] = self.batch_parallel
        data["ignoreIfSub"] = self.ignoreIfSub
        return data



@dataclass(frozen=True)
class TemplateJobNode(BaseExecutableNode):
    # Type field with default
    type: NodeType = field(default=NodeType.TEMPLATE_JOB, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    template_path: Optional[str] = None
    template_content: Optional[str] = None
    output_path: Optional[str] = None
    variables: Optional[JsonDict] = None
    engine: Optional[TemplateEngine] = None
    foreach: Optional[Dict[str, Any]] = None
    preprocessor: Optional[TemplatePreprocessor] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["template_path"] = self.template_path
        data["template_content"] = self.template_content
        data["output_path"] = self.output_path
        data["variables"] = self.variables
        data["engine"] = self.engine
        data["foreach"] = self.foreach
        data["preprocessor"] = self.preprocessor
        return data



@dataclass(frozen=True)
class TypescriptAstNode(BaseExecutableNode):
    # Type field with default
    type: NodeType = field(default=NodeType.TYPESCRIPT_AST, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    # Optional node-specific fields
    source: Optional[str] = None
    extractPatterns: Optional[List[str]] = None
    includeJSDoc: Optional[bool] = None
    parseMode: Optional[Literal["module", "script"]] = None
    batch: Optional[bool] = None
    sources: Optional[Dict[str, str]] = None
    batchInputKey: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["source"] = self.source
        data["extractPatterns"] = self.extractPatterns
        data["includeJSDoc"] = self.includeJSDoc
        data["parseMode"] = self.parseMode
        data["batch"] = self.batch
        data["sources"] = self.sources
        data["batchInputKey"] = self.batchInputKey
        return data



@dataclass(frozen=True)
class UserResponseNode(BaseExecutableNode):
    # Required node-specific fields
    prompt: str = field()
    timeout: int = field()
    # Type field with default
    type: NodeType = field(default=NodeType.USER_RESPONSE, init=False)
    # Base optional fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["type"] = self.type.value
        data["label"] = self.label
        data["flipped"] = self.flipped
        if self.metadata:
            data["metadata"] = self.metadata
        data["prompt"] = self.prompt
        data["timeout"] = self.timeout
        return data



@dataclass(frozen=True)
class PersonBatchJobNode(PersonJobNode):
    """Person batch job node - same as PersonJobNode but with different type."""
    type: NodeType = field(default=NodeType.PERSON_BATCH_JOB, init=False)


ExecutableNode = Union[
    ApiJobNode,
    CodeJobNode,
    ConditionNode,
    DBNode,
    EndpointNode,
    HookNode,
    IntegratedApiNode,
    JsonSchemaValidatorNode,
    PersonJobNode,
    StartNode,
    SubDiagramNode,
    TemplateJobNode,
    TypescriptAstNode,
    UserResponseNode,
    PersonBatchJobNode
]


def create_executable_node(
    node_type: NodeType,
    node_id: NodeID,
    position: Vec2,
    label: str = "",
    data: Optional[Dict[str, Any]] = None,
    flipped: bool = False,
    metadata: Optional[Dict[str, Any]] = None
) -> ExecutableNode:
    """Factory function to create typed executable nodes from diagram data."""
    data = data or {}

    if node_type == NodeType.API_JOB:
        return ApiJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            url=data.get("url"),
            method=data.get("method"),
            headers=data.get("headers", None),
            params=data.get("params", None),
            body=data.get("body", None),
            timeout=data.get("timeout", None),
            auth_type=data.get("auth_type", None),
            auth_config=data.get("auth_config", None),
        )
    

    if node_type == NodeType.CODE_JOB:
        return CodeJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            language=data.get("language"),
            filePath=data.get("filePath", None),
            code=data.get("code", None),
            functionName=data.get("functionName", None),
            timeout=data.get("timeout", None),
        )
    

    if node_type == NodeType.CONDITION:
        return ConditionNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            condition_type=data.get("condition_type", None),
            expression=data.get("expression", None),
            node_indices=data.get("node_indices", None),
        )
    

    if node_type == NodeType.DB:
        return DBNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            file=data.get("file", None),
            collection=data.get("collection", None),
            sub_type=data.get("sub_type"),
            operation=data.get("operation"),
            query=data.get("query", None),
            data=data.get("data", None),
            serialize_json=data.get("serialize_json", None),
            glob=data.get("glob", None),
            format=data.get("format", None),
        )
    

    if node_type == NodeType.ENDPOINT:
        return EndpointNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            save_to_file=data.get("save_to_file"),
            file_name=data.get("file_name", None),
        )
    

    if node_type == NodeType.HOOK:
        return HookNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            hook_type=data.get("hook_type"),
            command=data.get("command", None),
            args=data.get("args", None),
            env=data.get("env", None),
            cwd=data.get("cwd", None),
            url=data.get("url", None),
            method=data.get("method", None),
            headers=data.get("headers", None),
            script=data.get("script", None),
            function_name=data.get("function_name", None),
            file_path=data.get("file_path", None),
            format=data.get("format", None),
            timeout=data.get("timeout", None),
            retry_count=data.get("retry_count", None),
            retry_delay=data.get("retry_delay", None),
        )
    

    if node_type == NodeType.INTEGRATED_API:
        return IntegratedApiNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            provider=data.get("provider"),
            operation=data.get("operation"),
            config=data.get("config", None),
            resource_id=data.get("resource_id", None),
            timeout=data.get("timeout", None),
            max_retries=data.get("max_retries", None),
        )
    

    if node_type == NodeType.JSON_SCHEMA_VALIDATOR:
        return JsonSchemaValidatorNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            schema_path=data.get("schema_path", None),
            json_schema=data.get("json_schema", None),
            data_path=data.get("data_path", None),
            strict_mode=data.get("strict_mode", None),
            error_on_extra=data.get("error_on_extra", None),
        )
    

    if node_type == NodeType.PERSON_JOB:
        return PersonJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            person=data.get("person", None),
            first_only_prompt=data.get("first_only_prompt"),
            first_prompt_file=data.get("first_prompt_file", None),
            default_prompt=data.get("default_prompt", None),
            prompt_file=data.get("prompt_file", None),
            max_iteration=data.get("max_iteration"),
            memory_profile=data.get("memory_profile", None),
            memory_settings=data.get("memory_settings", None),
            tools=data.get("tools", None),
            text_format=data.get("text_format", None),
            text_format_file=data.get("text_format_file", None),
            batch=data.get("batch", None),
            batch_input_key=data.get("batch_input_key", None),
            batch_parallel=data.get("batch_parallel", None),
            max_concurrent=data.get("max_concurrent", None),
        )
    

    if node_type == NodeType.START:
        return StartNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            trigger_mode=data.get("trigger_mode"),
            custom_data=data.get("custom_data", None),
            output_data_structure=data.get("output_data_structure", None),
            hook_event=data.get("hook_event", None),
            hook_filters=data.get("hook_filters", None),
        )
    

    if node_type == NodeType.SUB_DIAGRAM:
        return SubDiagramNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            diagram_name=data.get("diagram_name", None),
            diagram_format=data.get("diagram_format", None),
            diagram_data=data.get("diagram_data", None),
            batch=data.get("batch", None),
            batch_input_key=data.get("batch_input_key", None),
            batch_parallel=data.get("batch_parallel", None),
            ignoreIfSub=data.get("ignoreIfSub", None),
        )
    

    if node_type == NodeType.TEMPLATE_JOB:
        return TemplateJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            template_path=data.get("template_path", None),
            template_content=data.get("template_content", None),
            output_path=data.get("output_path", None),
            variables=data.get("variables", None),
            engine=data.get("engine", None),
            foreach=data.get("foreach", None),
            preprocessor=data.get("preprocessor", None),
        )
    

    if node_type == NodeType.TYPESCRIPT_AST:
        return TypescriptAstNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            source=data.get("source", None),
            extractPatterns=data.get("extractPatterns", None),
            includeJSDoc=data.get("includeJSDoc", None),
            parseMode=data.get("parseMode", None),
            batch=data.get("batch", None),
            sources=data.get("sources", None),
            batchInputKey=data.get("batchInputKey", None),
        )
    

    if node_type == NodeType.USER_RESPONSE:
        return UserResponseNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            prompt=data.get("prompt"),
            timeout=data.get("timeout"),
        )
    

    if node_type == NodeType.PERSON_BATCH_JOB:
        return PersonBatchJobNode(
            id=node_id,
            position=position,
            label=label,
            flipped=flipped,
            metadata=metadata,
            person=data.get("person", None),
            first_only_prompt=data.get("first_only_prompt"),
            first_prompt_file=data.get("first_prompt_file", None),
            default_prompt=data.get("default_prompt", None),
            prompt_file=data.get("prompt_file", None),
            max_iteration=data.get("max_iteration"),
            memory_profile=data.get("memory_profile", None),
            memory_settings=data.get("memory_settings", None),
            tools=data.get("tools", None),
            text_format=data.get("text_format", None),
            text_format_file=data.get("text_format_file", None),
            batch=data.get("batch", None),
            batch_input_key=data.get("batch_input_key", None),
            batch_parallel=data.get("batch_parallel", None),
            max_concurrent=data.get("max_concurrent", None),
        )
    
    raise ValueError(f"Unknown node type: {node_type}")