"""
GENERATED FILE - DO NOT EDIT
Generated by backend integrations generation
Generated at: 2025-10-04T12:05:50.202642
Integration models for external services
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List, Union, TYPE_CHECKING
from .enums import ToolType

if TYPE_CHECKING:
    from .domain_models import LLMUsage

class IntegrationProvider(BaseModel):
    """IntegrationProvider integration model"""
    # Integration type: string
    enabled: bool = True

# Export all integrations
__all__ = [
    'IntegrationProvider',
]
