"""
Auto-generated static node type for json_schema_validator.
DO NOT EDIT THIS FILE DIRECTLY.
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, Literal

from dipeo.models.models import (
    NodeType, Vec2, NodeID, PersonID, MemoryConfig, MemorySettings, ToolConfig,
    HookTriggerMode, SupportedLanguage, HttpMethod, DBBlockSubType,
    NotionOperation, HookType, PersonLLMConfig, LLMService, ExtractPattern
)
from dipeo.core.static.generated_nodes import BaseExecutableNode


@dataclass(frozen=True)
class JsonSchemaValidatorNode(BaseExecutableNode):
    """Validate data against JSON schema"""
    type: NodeType = field(default=NodeType.json_schema_validator, init=False)
    schema_path: str = ""
    schema: Dict[str, Any] = {}
    data_path: str = ""
    strict_mode: bool = False
    error_on_extra: bool = False

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = super().to_dict()
        data["schema_path"] = self.schema_path
        data["schema"] = self.schema
        data["data_path"] = self.data_path
        data["strict_mode"] = self.strict_mode
        data["error_on_extra"] = self.error_on_extra
        return data