openapi: 3.0.3
info:
  title: DiPeO Backend API
  description: |
    DiPeO (Diagrammed People & Organizations) is a visual programming environment
    that executes agent diagrams through a unified backend execution engine.
    
    This API provides endpoints for:
    - Diagram execution with real-time WebSocket streaming
    - API key management for LLM providers
    - File operations and uploads
    - Conversation memory management
    - Real-time execution monitoring
    
    All diagram nodes execute server-side through the V2 API with consistent
    execution, centralized security, and WebSocket streaming for real-time updates.
  version: 2.0.1
  license:
    name: MIT

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.dipeo.io
    description: Production server (planned)

tags:
  - name: diagram
    description: Diagram execution and management operations
  - name: api-keys
    description: LLM API key management
  - name: files
    description: File upload and management
  - name: conversations
    description: Conversation memory and history
  - name: monitor
    description: Real-time execution monitoring

paths:



  /api/diagrams/convert:
    post:
      tags:
        - diagram
      summary: Convert diagram format
      description: Convert diagram between different formats (JSON, YAML, LLM-YAML, UML)
      operationId: convertDiagram
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - from_format
                - to_format
              properties:
                content:
                  type: string
                  description: The diagram content to convert
                from_format:
                  type: string
                  enum: ["yaml", "json", "llm-yaml", "uml"]
                  description: Source format
                to_format:
                  type: string
                  enum: ["yaml", "json", "llm-yaml", "uml"]
                  description: Target format
      responses:
        '200':
          description: Conversion successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  output:
                    type: string
                    description: Converted diagram content
                  message:
                    type: string
        '400':
          $ref: '#/components/responses/ValidationError'

  /api/diagrams/health:
    get:
      tags:
        - diagram
      summary: Health check
      description: Health check endpoint for V2 API
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  version:
                    type: string
                    example: "2.0"
                  timestamp:
                    type: string
                    format: date-time



  /api/files/upload:
    post:
      tags:
        - files
      summary: Upload file
      description: Upload a file to the server
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: File to upload
                target_path:
                  type: string
                  description: Optional target directory path
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  path:
                    type: string
                    description: Relative path where file was saved
                  size:
                    type: integer
                    description: File size in bytes
                  message:
                    type: string
        '500':
          $ref: '#/components/responses/InternalError'

  /api/conversations:
    get:
      tags:
        - conversations
      summary: Get conversations
      description: Get conversation data with pagination and filtering
      operationId: getConversations
      parameters:
        - name: personId
          in: query
          description: Filter by person ID
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of messages to return
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 50
        - name: offset
          in: query
          description: Number of messages to skip
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: search
          in: query
          description: Search term to filter messages
          schema:
            type: string
        - name: executionId
          in: query
          description: Filter by execution ID
          schema:
            type: string
        - name: showForgotten
          in: query
          description: Include forgotten messages
          schema:
            type: boolean
            default: false
        - name: startTime
          in: query
          description: Filter messages after this time
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          description: Filter messages before this time
          schema:
            type: string
            format: date-time
        - name: since
          in: query
          description: Get messages since this time (exclusive)
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Conversation data
          content:
            application/json:
              schema:
                type: object
                properties:
                  persons:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        person_id:
                          type: string
                        messages:
                          type: array
                          items:
                            $ref: '#/components/schemas/ConversationMessage'
                        total_messages:
                          type: integer
                        visible_messages:
                          type: integer
                        forgotten_messages:
                          type: integer
                        has_more:
                          type: boolean
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      tags:
        - conversations
      summary: Clear conversations
      description: Clear all conversation memory
      operationId: clearConversations
      responses:
        '200':
          description: Conversations cleared
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '500':
          $ref: '#/components/responses/InternalError'


  /metrics:
    get:
      summary: Prometheus metrics
      description: Expose Prometheus metrics
      operationId: getMetrics
      responses:
        '200':
          description: Prometheus metrics
          content:
            text/plain:
              schema:
                type: string
                description: Prometheus formatted metrics

components:
  schemas:
    DiagramNode:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
          description: Unique node identifier
          example: "node_123"
        type:
          type: string
          description: Node type (snake_case format, unified across frontend and backend)
          enum: ["start", "person_job", "person_batch_job", "condition", "db", "job", "endpoint"]
        data:
          type: object
          description: Node properties/configuration
          additionalProperties: true
        position:
          type: object
          properties:
            x:
              type: number
            y:
              type: number

    DiagramArrow:
      type: object
      required:
        - id
        - source
        - target
      properties:
        id:
          type: string
          description: Unique arrow identifier
        source:
          type: string
          description: Source node ID
        target:
          type: string
          description: Target node ID
        sourceHandle:
          type: string
          description: Source connection point identifier
        targetHandle:
          type: string
          description: Target connection point identifier
        label:
          type: string
          description: Arrow label (becomes variable name)
        data:
          type: object
          additionalProperties: true

    Person:
      type: object
      required:
        - id
        - apiKeyId
      properties:
        id:
          type: string
        name:
          type: string
        service:
          type: string
          enum: ["openai", "claude", "gemini", "grok"]
        apiKeyId:
          type: string
        modelName:
          type: string
        systemPrompt:
          type: string

    ApiKeyInfo:
      type: object
      properties:
        id:
          type: string
          example: "APIKEY_abc123"
        name:
          type: string
          example: "My OpenAI Key"
        service:
          type: string
          enum: ["openai", "claude", "gemini", "grok"]

    ConversationMessage:
      type: object
      properties:
        id:
          type: string
        role:
          type: string
          enum: ["user", "assistant", "system"]
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        execution_id:
          type: string
        node_id:
          type: string
        node_label:
          type: string
        token_count:
          type: integer
        input_tokens:
          type: integer
        output_tokens:
          type: integer
        cached_tokens:
          type: integer

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error message
        details:
          type: object
          additionalProperties: true
          description: Additional error details

  parameters:
    ApiKeyId:
      name: id
      in: path
      required: true
      description: API key identifier
      schema:
        type: string
        example: "APIKEY_abc123"

  responses:
    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            error: "Validation failed"
            details:
              field: "service"
              reason: "Invalid service name"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            error: "API key not found"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            error: "Internal server error"
            details:
              message: "An unexpected error occurred"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT authentication (planned for future release)