/**
 * GENERATED FILE - DO NOT EDIT
 * Generated by domain model field configs generation
 * Generated at: 2025-09-05T16:04:28.729678
 *
 * This file contains base field configurations generated from domain models.
 * To customize fields, use the override system in each node's config file.
 */

import type { UnifiedFieldDefinition } from '@/infrastructure/config/unifiedConfig';

export interface GeneratedFieldConfigs {
  [nodeType: string]: UnifiedFieldDefinition[];
}

export const GENERATED_FIELD_CONFIGS: GeneratedFieldConfigs = {
  'start': [
    {
      name: 'trigger_mode',
      type: 'select',
      label: 'Trigger Mode',
      required: true,
    },
    {
      name: 'custom_data',
      type: 'checkbox',
      label: 'Custom Data',
      required: false,
    },
    {
      name: 'output_data_structure',
      type: 'text',
      label: 'Output Data Structure',
      required: false,
    },
    {
      name: 'hook_event',
      type: 'text',
      label: 'Hook Event',
      required: false,
    },
    {
      name: 'hook_filters',
      type: 'text',
      label: 'Hook Filters',
      required: false,
    },
  ],
  'person_job': [
    {
      name: 'person',
      type: 'personSelect',
      label: 'Person',
      required: false,
    },
    {
      name: 'first_only_prompt',
      type: 'variableTextArea',
      label: 'First Only Prompt',
      required: true,
      placeholder: 'Enter first_only_prompt (supports variables)',
    },
    {
      name: 'first_prompt_file',
      type: 'text',
      label: 'First Prompt File',
      required: false,
    },
    {
      name: 'default_prompt',
      type: 'variableTextArea',
      label: 'Default Prompt',
      required: false,
      placeholder: 'Enter default_prompt (supports variables)',
    },
    {
      name: 'prompt_file',
      type: 'text',
      label: 'Prompt File',
      required: false,
    },
    {
      name: 'max_iteration',
      type: 'maxIteration',
      label: 'Max Iteration',
      required: true,
    },
    {
      name: 'memorize_to',
      type: 'text',
      label: 'Memorize To',
      required: true,
    },
    {
      name: 'at_most',
      type: 'number',
      label: 'At Most',
      required: true,
    },
    {
      name: 'tools',
      type: 'select',
      label: 'Tools',
      required: false,
    },
    {
      name: 'text_format',
      type: 'text',
      label: 'Text Format',
      required: false,
    },
    {
      name: 'text_format_file',
      type: 'text',
      label: 'Text Format File',
      required: false,
    },
    {
      name: 'batch',
      type: 'checkbox',
      label: 'Batch',
      required: false,
    },
    {
      name: 'batch_input_key',
      type: 'text',
      label: 'Batch Input Key',
      required: false,
    },
    {
      name: 'batch_parallel',
      type: 'checkbox',
      label: 'Batch Parallel',
      required: false,
    },
    {
      name: 'max_concurrent',
      type: 'number',
      label: 'Max Concurrent',
      required: false,
    },
  ],
  'condition': [
    {
      name: 'condition_type',
      type: 'text',
      label: 'Condition Type',
      required: false,
    },
    {
      name: 'expression',
      type: 'variableTextArea',
      label: 'Expression',
      required: false,
      placeholder: 'Enter expression (supports variables)',
    },
    {
      name: 'node_indices',
      type: 'text',
      label: 'Node Indices',
      required: false,
    },
    {
      name: 'expose_index_as',
      type: 'text',
      label: 'Expose Index As',
      required: false,
    },
    {
      name: 'skippable',
      type: 'checkbox',
      label: 'Skippable',
      required: false,
    },
    {
      name: 'person',
      type: 'personSelect',
      label: 'Person',
      required: false,
    },
    {
      name: 'judge_by',
      type: 'text',
      label: 'Judge By',
      required: false,
    },
    {
      name: 'judge_by_file',
      type: 'text',
      label: 'Judge By File',
      required: false,
    },
    {
      name: 'memorize_to',
      type: 'text',
      label: 'Memorize To',
      required: false,
    },
    {
      name: 'at_most',
      type: 'number',
      label: 'At Most',
      required: false,
    },
  ],
  'endpoint': [
    {
      name: 'save_to_file',
      type: 'checkbox',
      label: 'Save To File',
      required: true,
    },
    {
      name: 'file_name',
      type: 'text',
      label: 'File Name',
      required: false,
    },
  ],
  'db': [
    {
      name: 'file',
      type: 'text',
      label: 'File',
      required: false,
    },
    {
      name: 'collection',
      type: 'text',
      label: 'Collection',
      required: false,
    },
    {
      name: 'sub_type',
      type: 'select',
      label: 'Sub Type',
      required: true,
    },
    {
      name: 'operation',
      type: 'text',
      label: 'Operation',
      required: true,
    },
    {
      name: 'query',
      type: 'variableTextArea',
      label: 'Query',
      required: false,
      placeholder: 'Enter query (supports variables)',
    },
    {
      name: 'data',
      type: 'text',
      label: 'Data',
      required: false,
    },
    {
      name: 'serialize_json',
      type: 'checkbox',
      label: 'Serialize Json',
      required: false,
    },
    {
      name: 'glob',
      type: 'checkbox',
      label: 'Glob',
      required: false,
    },
    {
      name: 'format',
      type: 'text',
      label: 'Format',
      required: false,
    },
  ],
  'code_job': [
    {
      name: 'language',
      type: 'select',
      label: 'Language',
      required: true,
    },
    {
      name: 'filePath',
      type: 'filepath',
      label: 'Filepath',
      required: false,
      placeholder: 'path/to/file',
    },
    {
      name: 'code',
      type: 'code',
      label: 'Code',
      required: false,
    },
    {
      name: 'functionName',
      type: 'text',
      label: 'Functionname',
      required: false,
    },
    {
      name: 'timeout',
      type: 'number',
      label: 'Timeout',
      required: false,
    },
  ],
  'api_job': [
    {
      name: 'url',
      type: 'url',
      label: 'Url',
      required: true,
    },
    {
      name: 'method',
      type: 'select',
      label: 'Method',
      required: true,
    },
    {
      name: 'headers',
      type: 'text',
      label: 'Headers',
      required: false,
    },
    {
      name: 'params',
      type: 'text',
      label: 'Params',
      required: false,
    },
    {
      name: 'body',
      type: 'text',
      label: 'Body',
      required: false,
    },
    {
      name: 'timeout',
      type: 'number',
      label: 'Timeout',
      required: false,
    },
    {
      name: 'auth_type',
      type: 'text',
      label: 'Auth Type',
      required: false,
    },
    {
      name: 'auth_config',
      type: 'text',
      label: 'Auth Config',
      required: false,
    },
  ],
  'user_response': [
    {
      name: 'prompt',
      type: 'variableTextArea',
      label: 'Prompt',
      required: true,
      placeholder: 'Enter prompt (supports variables)',
    },
    {
      name: 'timeout',
      type: 'number',
      label: 'Timeout',
      required: true,
    },
  ],
  'hook': [
    {
      name: 'hook_type',
      type: 'select',
      label: 'Hook Type',
      required: true,
    },
    {
      name: 'command',
      type: 'text',
      label: 'Command',
      required: false,
    },
    {
      name: 'args',
      type: 'text',
      label: 'Args',
      required: false,
    },
    {
      name: 'env',
      type: 'text',
      label: 'Env',
      required: false,
    },
    {
      name: 'cwd',
      type: 'text',
      label: 'Cwd',
      required: false,
    },
    {
      name: 'url',
      type: 'url',
      label: 'Url',
      required: false,
    },
    {
      name: 'method',
      type: 'select',
      label: 'Method',
      required: false,
    },
    {
      name: 'headers',
      type: 'text',
      label: 'Headers',
      required: false,
    },
    {
      name: 'script',
      type: 'code',
      label: 'Script',
      required: false,
    },
    {
      name: 'function_name',
      type: 'text',
      label: 'Function Name',
      required: false,
    },
    {
      name: 'file_path',
      type: 'filepath',
      label: 'File Path',
      required: false,
      placeholder: 'path/to/file',
    },
    {
      name: 'format',
      type: 'text',
      label: 'Format',
      required: false,
    },
    {
      name: 'timeout',
      type: 'number',
      label: 'Timeout',
      required: false,
    },
    {
      name: 'retry_count',
      type: 'number',
      label: 'Retry Count',
      required: false,
    },
    {
      name: 'retry_delay',
      type: 'number',
      label: 'Retry Delay',
      required: false,
    },
  ],
  'template_job': [
    {
      name: 'template_path',
      type: 'text',
      label: 'Template Path',
      required: false,
    },
    {
      name: 'template_content',
      type: 'text',
      label: 'Template Content',
      required: false,
    },
    {
      name: 'output_path',
      type: 'text',
      label: 'Output Path',
      required: false,
    },
    {
      name: 'variables',
      type: 'text',
      label: 'Variables',
      required: false,
    },
    {
      name: 'engine',
      type: 'text',
      label: 'Engine',
      required: false,
    },
    {
      name: 'foreach',
      type: 'number',
      label: 'Foreach',
      required: false,
    },
    {
      name: 'preprocessor',
      type: 'text',
      label: 'Preprocessor',
      required: false,
    },
  ],
  'json_schema_validator': [
    {
      name: 'schema_path',
      type: 'text',
      label: 'Schema Path',
      required: false,
    },
    {
      name: 'json_schema',
      type: 'text',
      label: 'Json Schema',
      required: false,
    },
    {
      name: 'data_path',
      type: 'text',
      label: 'Data Path',
      required: false,
    },
    {
      name: 'strict_mode',
      type: 'checkbox',
      label: 'Strict Mode',
      required: false,
    },
    {
      name: 'error_on_extra',
      type: 'checkbox',
      label: 'Error On Extra',
      required: false,
    },
  ],
  'typescript_ast': [
    {
      name: 'source',
      type: 'text',
      label: 'Source',
      required: false,
    },
    {
      name: 'extractPatterns',
      type: 'text',
      label: 'Extractpatterns',
      required: false,
    },
    {
      name: 'includeJSDoc',
      type: 'checkbox',
      label: 'Includejsdoc',
      required: false,
    },
    {
      name: 'parseMode',
      type: 'text',
      label: 'Parsemode',
      required: false,
    },
    {
      name: 'batch',
      type: 'checkbox',
      label: 'Batch',
      required: false,
    },
    {
      name: 'sources',
      type: 'text',
      label: 'Sources',
      required: false,
    },
    {
      name: 'batchInputKey',
      type: 'text',
      label: 'Batchinputkey',
      required: false,
    },
  ],
  'sub_diagram': [
    {
      name: 'diagram_name',
      type: 'text',
      label: 'Diagram Name',
      required: false,
    },
    {
      name: 'diagram_format',
      type: 'select',
      label: 'Diagram Format',
      required: false,
    },
    {
      name: 'diagram_data',
      type: 'text',
      label: 'Diagram Data',
      required: false,
    },
    {
      name: 'passInputData',
      type: 'checkbox',
      label: 'Passinputdata',
      required: false,
    },
    {
      name: 'batch',
      type: 'checkbox',
      label: 'Batch',
      required: false,
    },
    {
      name: 'batch_input_key',
      type: 'text',
      label: 'Batch Input Key',
      required: false,
    },
    {
      name: 'batch_parallel',
      type: 'checkbox',
      label: 'Batch Parallel',
      required: false,
    },
    {
      name: 'ignoreIfSub',
      type: 'checkbox',
      label: 'Ignoreifsub',
      required: false,
    },
  ],
  'integrated_api': [
    {
      name: 'provider',
      type: 'text',
      label: 'Provider',
      required: true,
    },
    {
      name: 'operation',
      type: 'text',
      label: 'Operation',
      required: true,
    },
    {
      name: 'config',
      type: 'text',
      label: 'Config',
      required: false,
    },
    {
      name: 'resource_id',
      type: 'text',
      label: 'Resource Id',
      required: false,
    },
    {
      name: 'timeout',
      type: 'number',
      label: 'Timeout',
      required: false,
    },
    {
      name: 'max_retries',
      type: 'number',
      label: 'Max Retries',
      required: false,
    },
  ],
};

/**
 * Get generated field configurations for a node type
 */
export function getGeneratedFields(nodeType: string): UnifiedFieldDefinition[] {
  return GENERATED_FIELD_CONFIGS[nodeType] || [];
}
