// Auto-generated node registry
// DO NOT EDIT - This file is automatically generated by the codegen system
import { registerNodeConfig } from '@/domain/diagram/config/nodeRegistry';

import { apiJobConfig } from '@/__generated__/nodes/ApiJobConfig';
import { codeJobConfig } from '@/__generated__/nodes/CodeJobConfig';
import { conditionConfig } from '@/__generated__/nodes/ConditionConfig';
import { dbConfig } from '@/__generated__/nodes/DbConfig';
import { endpointConfig } from '@/__generated__/nodes/EndpointConfig';
import { hookConfig } from '@/__generated__/nodes/HookConfig';
import { integratedApiConfig } from '@/__generated__/nodes/IntegratedApiConfig';
import { jsonSchemaValidatorConfig } from '@/__generated__/nodes/JsonSchemaValidatorConfig';
import { personBatchJobConfig } from '@/__generated__/nodes/PersonBatchJobConfig';
import { personJobConfig } from '@/__generated__/nodes/PersonJobConfig';
import { startConfig } from '@/__generated__/nodes/StartConfig';
import { subDiagramConfig } from '@/__generated__/nodes/SubDiagramConfig';
import { templateJobConfig } from '@/__generated__/nodes/TemplateJobConfig';
import { typescriptAstConfig } from '@/__generated__/nodes/TypescriptAstConfig';
import { userResponseConfig } from '@/__generated__/nodes/UserResponseConfig';

export function registerAllNodes() {
  registerNodeConfig(apiJobConfig);
  registerNodeConfig(codeJobConfig);
  registerNodeConfig(conditionConfig);
  registerNodeConfig(dbConfig);
  registerNodeConfig(endpointConfig);
  registerNodeConfig(hookConfig);
  registerNodeConfig(integratedApiConfig);
  registerNodeConfig(jsonSchemaValidatorConfig);
  registerNodeConfig(personBatchJobConfig);
  registerNodeConfig(personJobConfig);
  registerNodeConfig(startConfig);
  registerNodeConfig(subDiagramConfig);
  registerNodeConfig(templateJobConfig);
  registerNodeConfig(typescriptAstConfig);
  registerNodeConfig(userResponseConfig);
}

// Call this on app initialization
registerAllNodes();
