[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dipeo-services"
version = "0.1.0"
authors = [{name = "DiPeO Team"}]
description = "Domain services for DiPeO - shared between server and CLI"
readme = "README.md"
requires-python = ">=3.13"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "dipeo-core",
    "dipeo-domain",
    "pydantic>=2.10.0",
]
keywords = ["dipeo", "services", "domain", "business-logic"]

[project.urls]
Homepage = "https://github.com/dipeo/dipeo"
Repository = "https://github.com/dipeo/dipeo"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
dipeo_services = ["py.typed"]