#!/usr/bin/env python3
"""Render key codegen templates to validate context compatibility."""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

from dipeo.infrastructure.codegen.templates.drivers.factory import get_template_service

BASE_TEMPLATE_DIR = Path("projects/codegen/templates")
IR_DIR = Path("projects/codegen/ir")


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


async def render(service, template_path: str, context: dict[str, Any]) -> None:
    try:
        await service.render_template(template_path, context)
    except Exception as e:
        print(f"  ✗ ERROR rendering {template_path}: {e}")
        import traceback
        traceback.print_exc()
        raise


async def render_backend_templates(service) -> None:
    backend_ir = load_json(IR_DIR / "backend_ir.json")
    backend_ctx = dict(backend_ir)
    backend_ctx.setdefault("now", backend_ir.get("generated_at"))

    templates = [
        "backend/domain_models.j2",
        "backend/node_factory.j2",
        "backend/conversions.j2",
        "backend/integrations.j2",
        "backend/enums.j2",
        "backend/generated_nodes.j2",
        "backend/unified_nodes_init.j2",
    ]

    for template in templates:
        await render(service, template, dict(backend_ctx))


async def render_frontend_templates(service) -> None:
    frontend_ir = load_json(IR_DIR / "frontend_ir.json")
    frontend_ctx = dict(frontend_ir)
    frontend_ctx.setdefault("now", frontend_ir.get("generated_at"))

    templates = [
        "frontend/graphql-queries-simplified.j2",
        "frontend/zod_schemas_simplified.j2",
        "frontend/field_configs.j2",
    ]

    for template in templates:
        await render(service, template, dict(frontend_ctx))


async def render_strawberry_templates(service) -> None:
    strawberry_ir = load_json(IR_DIR / "strawberry_ir.json")
    base_ctx = dict(strawberry_ir)
    base_ctx.setdefault("now", strawberry_ir.get("generated_at"))

    templates_with_extras = [
        ("strawberry/strawberry_types.j2", {"generated_warning": "Generated by verification"}),
        ("strawberry/strawberry_scalars.j2", {"generated_warning": "Generated by verification"}),
        ("strawberry/scalar_aliases.j2", {"generated_warning": "Generated by verification"}),
        ("strawberry/strawberry_domain_simplified.j2", {"generated_warning": "Generated by verification"}),
        ("strawberry/strawberry_inputs.j2", {"generated_warning": "Generated by verification"}),
        ("strawberry/strawberry_enums.j2", {"generated_warning": "Generated by verification"}),
        ("strawberry/strawberry_mutations.j2", {"generated_warning": "Generated by verification"}),
        ("strawberry/strawberry_results.j2", {"generated_warning": "Generated by verification"}),
        ("strawberry/strawberry_schema_from_operations.j2", {"generated_warning": "Generated by verification"}),
        ("strawberry/python-graphql-operations.j2", {"generated_warning": "Generated by verification"}),
    ]

    for template, extra in templates_with_extras:
        context = dict(base_ctx)
        context.update(extra)
        await render(service, template, context)


async def main() -> None:
    service = get_template_service()

    failed_templates = []

    print("\n=== Rendering Backend Templates ===")
    try:
        await render_backend_templates(service)
    except Exception as e:
        failed_templates.append(("backend", str(e)))
        print(f"\nFailed to render backend templates: {e}")

    print("\n=== Rendering Frontend Templates ===")
    try:
        await render_frontend_templates(service)
    except Exception as e:
        failed_templates.append(("frontend", str(e)))
        print(f"\nFailed to render frontend templates: {e}")

    print("\n=== Rendering Strawberry Templates ===")
    try:
        await render_strawberry_templates(service)
    except Exception as e:
        failed_templates.append(("strawberry", str(e)))
        print(f"\nFailed to render strawberry templates: {e}")

    if failed_templates:
        print("\n=== SUMMARY: Template Rendering Failed ===")
        for category, error in failed_templates:
            print(f"  ✗ {category}: {error}")
        import sys
        sys.exit(1)
    else:
        print("\n=== SUMMARY: All Templates Rendered Successfully ===")


if __name__ == "__main__":
    asyncio.run(main())
