// Generated field configuration for person_job
import type { UnifiedFieldDefinition } from '@/core/config/unifiedConfig';

export const personJobFields: UnifiedFieldDefinition[] = [
  {
    name: 'default_prompt',
    type: 'textarea',
    label: 'Default Prompt',
    required: false,
    placeholder: 'Enter prompt template...',
    description: 'Default Prompt configuration',
    rows: 10,
    column: 2,
  },
  {
    name: 'first_only_prompt',
    type: 'textarea',
    label: 'First Only Prompt',
    required: true,
    placeholder: 'Enter prompt template...',
    description: 'First Only Prompt configuration',
    rows: 10,
    column: 2,
  },
  {
    name: 'max_iteration',
    type: 'number',
    label: 'Max Iteration',
    required: true,
    defaultValue: 1,
    description: 'Max Iteration configuration',
    min: 1,
  },
  {
    name: 'memory_config',
    type: 'code',
    label: 'Memory Config',
    required: false,
    description: 'Memory Config configuration (deprecated - use memory_profile or memory_settings)',
  },
  {
    name: 'memory_profile',
    type: 'select',
    label: 'Memory Profile',
    required: false,
    defaultValue: "FOCUSED",
    description: 'Memory profile for conversation context',
    options: [
      { value: 'FULL', label: 'Full 🧠 - No limits, see everything' },
      { value: 'FOCUSED', label: 'Focused 🎯 - Last 20 messages, conversation pairs' },
      { value: 'MINIMAL', label: 'Minimal 💭 - Last 5 messages, system + direct only' },
      { value: 'GOLDFISH', label: 'Goldfish 🐠 - Last 1-2 exchanges only' },
      { value: 'CUSTOM', label: 'Custom ⚙️ - Use memory_settings below' },
    ],
  },
  {
    name: 'memory_settings',
    type: 'group',
    label: 'Memory Settings',
    required: false,
    description: 'Memory Settings configuration (only used when memory_profile is CUSTOM)',
    conditional: {
      field: 'memory_profile',
      values: ['CUSTOM']
    },
    nestedFields: [
      {
        name: 'view',
        type: 'select',
        label: 'View',
        required: false,
        description: 'Memory view mode',
        defaultValue: "all_involved",
        uiConfig: {
          inputType: 'select',
          options: [
            { value: 'all_involved', label: 'All Involved - Messages where person is sender or recipient' },
            { value: 'sent_by_me', label: 'Sent By Me - Messages I sent' },
            { value: 'sent_to_me', label: 'Sent To Me - Messages sent to me' },
            { value: 'system_and_me', label: 'System and Me - System messages and my interactions' },
            { value: 'conversation_pairs', label: 'Conversation Pairs - Request/response pairs' },
            { value: 'all_messages', label: 'All Messages - All messages in conversation' },
          ],
        },
      },
      {
        name: 'max_messages',
        type: 'number',
        label: 'Max Messages',
        required: false,
        description: 'Maximum number of messages to include',
        uiConfig: {
          inputType: 'number',
          min: 1,
        },
      },
      {
        name: 'preserve_system',
        type: 'checkbox',
        label: 'Preserve System',
        required: false,
        description: 'Preserve system messages',
        defaultValue: false,
        uiConfig: {
          inputType: 'checkbox',
        },
      },
    ],
  },
  {
    name: 'person',
    type: 'personSelect',
    label: 'Person',
    required: false,
    description: 'Person configuration',
  },
  {
    name: 'tools',
    type: 'select',
    label: 'Tools',
    required: false,
    defaultValue: "none",
    description: 'Tools available to the AI agent',
    options: [
      { value: 'none', label: 'None - No tools' },
      { value: 'image', label: 'Image - Image generation capabilities' },
      { value: 'websearch', label: 'Web Search - Search the internet' },
    ],
  },
];