#!/usr/bin/env python3
"""
Generated by DiPeO Diagram-to-Python Exporter
This is a standalone Python script that can be run without DiPeO.

To run: python <script>.py
"""

import asyncio
import os
from pathlib import Path

from openai import AsyncOpenAI


async def main():
    """Main execution function."""

    # Initialize clients
    openai_client = AsyncOpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

    # start
    print("Starting execution...")

    # ask_name
    # Note: timeout=30s not implemented in export
    ask_name_output = input("What is your name?")

    # ask_age
    # Note: timeout=30s not implemented in export
    ask_age_output = input("How old are you?")

    # greet
    response = await openai_client.chat.completions.create(
        model="gpt-5-nano-2025-08-07",
        messages=[
            {
                "role": "user",
                "content": f"Generate a personalized greeting for {ask_name_output} who is {ask_age_output} years old. Be friendly and warm!",
            }
        ],
    )
    greet_output = response.choices[0].message.content

    # endpoint
    # Save result to file
    output_path = Path("files/results/greeting.txt")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(str(greet_output))
    print(f"✅ Saved output to {output_path}")

    print("✅ Execution complete")


if __name__ == "__main__":
    asyncio.run(main())
