/**
 * Execution and event-related enumerations
 */

/**
 * Unified status enum for both executions and nodes
 * Note: MAXITER_REACHED only applies to node contexts
 */
export enum Status {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  ABORTED = 'ABORTED',
  SKIPPED = 'SKIPPED',
  MAXITER_REACHED = 'MAXITER_REACHED'
}


export enum EventType {
  // Execution lifecycle
  EXECUTION_STARTED = 'EXECUTION_STARTED',
  EXECUTION_COMPLETED = 'EXECUTION_COMPLETED',
  EXECUTION_ERROR = 'EXECUTION_ERROR',
  EXECUTION_STATUS_CHANGED = 'EXECUTION_STATUS_CHANGED',
  
  // Node lifecycle
  NODE_STARTED = 'NODE_STARTED',
  NODE_COMPLETED = 'NODE_COMPLETED',
  NODE_ERROR = 'NODE_ERROR',
  NODE_OUTPUT = 'NODE_OUTPUT',
  NODE_STATUS_CHANGED = 'NODE_STATUS_CHANGED',
  NODE_PROGRESS = 'NODE_PROGRESS',
  
  // Metrics and monitoring
  METRICS_COLLECTED = 'METRICS_COLLECTED',
  OPTIMIZATION_SUGGESTED = 'OPTIMIZATION_SUGGESTED',
  
  // External integrations
  WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED',
  
  // Interactive
  INTERACTIVE_PROMPT = 'INTERACTIVE_PROMPT',
  INTERACTIVE_RESPONSE = 'INTERACTIVE_RESPONSE',
  
  // Logging and updates
  EXECUTION_UPDATE = 'EXECUTION_UPDATE',
  EXECUTION_LOG = 'EXECUTION_LOG',
  
  // WebSocket maintenance
  KEEPALIVE = 'KEEPALIVE'
}