"""
Auto-generated static node type for person_job.
DO NOT EDIT THIS FILE DIRECTLY.
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, Literal

from dipeo.models.models import (
    NodeType, Vec2, NodeID, PersonID, MemoryConfig, MemorySettings, ToolConfig,
    HookTriggerMode, SupportedLanguage, HttpMethod, DBBlockSubType,
    NotionOperation, HookType, PersonLLMConfig, LLMService
)


@dataclass(frozen=True)
class PersonJobNode:
    """Execute tasks using AI language models"""
    # Required base fields first
    id: NodeID
    position: Vec2
    
    # Required node-specific fields
    first_only_prompt: str
    max_iteration: float
    
    # Optional base fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    
    # Node type (fixed for this node class)
    type: NodeType = field(default=NodeType.person_job, init=False)
    
    # Optional node-specific fields
    person: str = ""
    default_prompt: str = ""
    memory_config: Dict[str, Any] = field(default_factory=dict)
    memory_settings: Dict[str, Any] = field(default_factory=dict)
    tools: List[Any] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = {
            "id": self.id,
            "type": self.type.value,
            "position": {"x": self.position.x, "y": self.position.y},
            "label": self.label,
            "flipped": self.flipped
        }
        if self.metadata:
            data["metadata"] = self.metadata
            
        # Add node-specific fields
        data["person"] = self.person
        data["first_only_prompt"] = self.first_only_prompt
        data["default_prompt"] = self.default_prompt
        data["max_iteration"] = self.max_iteration
        data["memory_config"] = self.memory_config
        data["memory_settings"] = self.memory_settings
        data["tools"] = self.tools
        return data