"""
Auto-generated static node type for typescript_ast.
DO NOT EDIT THIS FILE DIRECTLY.
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, Literal

from dipeo.diagram_generated.domain_models import (
    Vec2, NodeID, PersonID, MemorySettings, ToolConfig, PersonLLMConfig
)
from dipeo.diagram_generated.enums import (
    NodeType, HookTriggerMode, SupportedLanguage, HttpMethod, 
    DBBlockSubType, NotionOperation, HookType, LLMService
)


@dataclass(frozen=True)
class TypescriptAstNode:
    """Parses TypeScript source code and extracts AST, interfaces, types, and enums"""
    # Required base fields first
    id: NodeID
    position: Vec2
    
    # Required node-specific fields
    source: str
    
    # Optional base fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    
    # Node type (fixed for this node class)
    type: NodeType = field(default=NodeType.TYPESCRIPT_AST, init=False)
    
    # Optional node-specific fields
    extractPatterns: List[Any] = field(default_factory=list)
    includeJSDoc: bool = False
    parseMode: str = None
    transformEnums: bool = False
    flattenOutput: bool = False
    outputFormat: str = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = {
            "id": self.id,
            "type": self.type.value,
            "position": {"x": self.position.x, "y": self.position.y},
            "label": self.label,
            "flipped": self.flipped
        }
        if self.metadata:
            data["metadata"] = self.metadata
            
        # Add node-specific fields
        data["source"] = self.source
        data["extractPatterns"] = self.extractPatterns
        data["includeJSDoc"] = self.includeJSDoc
        data["parseMode"] = self.parseMode
        data["transformEnums"] = self.transformEnums
        data["flattenOutput"] = self.flattenOutput
        data["outputFormat"] = self.outputFormat
        return data