







"""
Auto-generated static node type for user_response.
DO NOT EDIT THIS FILE DIRECTLY.
"""

from dataclasses import *
from typing import *

from ..domain_models import *
from ..enums import *
from ..integrations import *


@dataclass(frozen=True)
class UserResponseNode:
    """Collect user input"""
    # Required base fields first
    id: NodeID
    position: Vec2
    
    # Required node-specific fields
    prompt: str
    
    # Optional base fields
    label: str = ""
    flipped: bool = False
    metadata: Optional[Dict[str, Any]] = None
    
    # Node type (fixed for this node class)
    type: NodeType = field(default=NodeType.USER_RESPONSE, init=False)
    
    # Optional node-specific fields
    timeout: int = 0

    def to_dict(self) -> Dict[str, Any]:
        """Convert node to dictionary representation."""
        data = {
            "id": self.id,
            "type": self.type.value,
            "position": {"x": self.position.x, "y": self.position.y},
            "label": self.label,
            "flipped": self.flipped
        }
        if self.metadata:
            data["metadata"] = self.metadata
            
        # Add node-specific fields
        data["prompt"] = self.prompt
        data["timeout"] = self.timeout
        return data