# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  codejob.schema.json
#   timestamp: 2025-09-06T03:56:13+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SupportedLanguage(Enum):
    python = 'python'
    typescript = 'typescript'
    bash = 'bash'
    shell = 'shell'


class CodeJobNodeData(BaseModel):
    """
    Configuration data for CodeJob nodes that execute code
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    code: str | None = Field(
        None, description='Inline code or path to external file'
    )
    filePath: str | None = Field(
        None, description="External code file path (e.g., 'files/code/processor.py')"
    )
    flipped: bool | None = None
    functionName: str | None = Field(
        None, description='Function to call in external file (required with filePath)'
    )
    label: str
    language: SupportedLanguage = Field(
        ..., description='Programming language: python, typescript, bash, or shell'
    )
    timeout: float | None = Field(
        None, description='Execution timeout in seconds (default: 60)'
    )


class Model(RootModel[CodeJobNodeData]):
    root: CodeJobNodeData
