# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  db.schema.json
#   timestamp: 2025-08-03T13:49:28+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, RootModel


class RecordStringAny(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )


class DBBlockSubType(Enum):
    fixed_prompt = 'fixed_prompt'
    file = 'file'
    code = 'code'
    api_tool = 'api_tool'


class DBNodeData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection: Optional[str] = None
    data: Optional[RecordStringAny] = None
    file: Optional[Union[List[str], str]] = None
    flipped: Optional[bool] = None
    label: str
    operation: str
    query: Optional[str] = None
    serialize_json: Optional[bool] = None
    sub_type: DBBlockSubType


class Model(RootModel[DBNodeData]):
    root: DBNodeData
