# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  endpoint.schema.json
#   timestamp: 2025-08-06T11:32:10+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel


class EndpointNodeData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_name: Optional[str] = None
    flipped: Optional[bool] = None
    label: str
    save_to_file: bool


class Model(RootModel[EndpointNodeData]):
    root: EndpointNodeData
