# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  jsonschemavalidator.schema.json
#   timestamp: 2025-09-06T03:56:13+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel


class JsonDict(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )


class JsonSchemaValidatorNodeData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data_path: str | None = None
    error_on_extra: bool | None = None
    flipped: bool | None = None
    json_schema: JsonDict | None = None
    label: str
    schema_path: str | None = None
    strict_mode: bool | None = None


class Model(RootModel[JsonSchemaValidatorNodeData]):
    root: JsonSchemaValidatorNodeData
