# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  notion.schema.json
#   timestamp: 2025-08-05T08:06:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel


class NotionOperation(Enum):
    create_page = 'create_page'
    update_page = 'update_page'
    get_page = 'get_page'
    query_database = 'query_database'


class NotionNodeData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    api_key: str
    database_id: str
    flipped: Optional[bool] = None
    label: str
    operation: NotionOperation
    page_id: Optional[str] = None


class Model(RootModel[NotionNodeData]):
    root: NotionNodeData
