# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  personjob.schema.json
#   timestamp: 2025-09-06T03:56:11+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Tools(Enum):
    """
    LLM tools to enable (web_search_preview, etc.)
    """

    image = 'image'
    none = 'none'
    websearch = 'websearch'


class PersonID(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field__brand: Literal['PersonID'] = Field(..., alias='__brand')


class PersonJobNodeData(BaseModel):
    """
    Configuration data for PersonJob nodes that execute LLM agents
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    at_most: float
    batch: bool | None = Field(
        None, description='Enable batch processing for arrays'
    )
    batch_input_key: str | None = Field(
        None, description='Array variable name for batch processing'
    )
    batch_parallel: bool | None = Field(
        None, description='Execute batch items in parallel'
    )
    default_prompt: str | None = Field(
        None,
        description='Prompt template using {{variable}} syntax for subsequent iterations',
    )
    first_only_prompt: str = Field(
        ...,
        description='Special prompt for first iteration only, supports {{variable}} syntax',
    )
    first_prompt_file: str | None = Field(
        None,
        description='External prompt file for first iteration only (overrides first_only_prompt)',
    )
    flipped: bool | None = None
    label: str
    max_concurrent: float | None = Field(
        None, description='Maximum concurrent batch executions'
    )
    max_iteration: float = Field(
        ..., description='Maximum conversation turns (default: 1)'
    )
    memorize_to: str
    person: PersonID | None = Field(
        None, description="Reference to agent defined in 'persons' section"
    )
    prompt_file: str | None = Field(
        None,
        description='External prompt file in files/prompts/ (overrides inline prompts)',
    )
    text_format: str | None = Field(
        None, description='Pydantic model name for structured output'
    )
    text_format_file: str | None = Field(
        None,
        description='External Python file with Pydantic models (overrides text_format)',
    )
    tools: Tools | None = Field(
        None, description='LLM tools to enable (web_search_preview, etc.)'
    )


class Model(RootModel[PersonJobNodeData]):
    root: PersonJobNodeData
