# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  start.schema.json
#   timestamp: 2025-08-06T11:32:10+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel


class RecordStringAny(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )


class RecordStringString(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )


class HookTriggerMode(Enum):
    none = 'none'
    manual = 'manual'
    hook = 'hook'


class RecordStringStringNumberBoolean(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )


class StartNodeData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    custom_data: Optional[RecordStringStringNumberBoolean] = None
    flipped: Optional[bool] = None
    hook_event: Optional[str] = None
    hook_filters: Optional[RecordStringAny] = None
    label: str
    output_data_structure: Optional[RecordStringString] = None
    trigger_mode: HookTriggerMode


class Model(RootModel[StartNodeData]):
    root: StartNodeData
