# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  templatejob.schema.json
#   timestamp: 2025-08-03T12:10:49+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel


class Engine(Enum):
    handlebars = 'handlebars'
    internal = 'internal'
    jinja2 = 'jinja2'


class RecordStringAny(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )


class TemplateJobNodeData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    engine: Optional[Engine] = None
    flipped: Optional[bool] = None
    label: str
    output_path: Optional[str] = None
    template_content: Optional[str] = None
    template_path: Optional[str] = None
    variables: Optional[RecordStringAny] = None


class Model(RootModel[TemplateJobNodeData]):
    root: TemplateJobNodeData
