# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  typescriptast.schema.json
#   timestamp: 2025-09-06T03:56:12+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class RecordStringString(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )


class ParseMode(Enum):
    module = 'module'
    script = 'script'


class TypescriptAstNodeData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    batch: bool | None = None
    batchInputKey: str | None = None
    extractPatterns: list[str] | None = None
    flipped: bool | None = None
    includeJSDoc: bool | None = None
    label: str
    parseMode: ParseMode | None = None
    source: str | None = None
    sources: RecordStringString | None = None


class Model(RootModel[TypescriptAstNodeData]):
    root: TypescriptAstNodeData
