# Auto-generated from JSON Schema
# DO NOT EDIT MANUALLY

# generated by datamodel-codegen:
#   filename:  userresponse.schema.json
#   timestamp: 2025-09-07T09:54:36+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel


class UserResponseNodeData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flipped: Optional[bool] = None
    label: str
    prompt: str
    timeout: float


class Model(RootModel[UserResponseNodeData]):
    root: UserResponseNodeData
