// Auto-generated file. Do not edit manually.
// Generated by projects/codegen/code/models/generate_typescript_indexes.py

import { NodeSpecificationRegistry } from '../types.js';
import { apiJobSpec } from './api-job.spec.js';
import { codeJobSpec } from './code-job.spec.js';
import { conditionSpec } from './condition.spec.js';
import { dbSpec } from './db.spec.js';
import { endpointSpec } from './endpoint.spec.js';
import { hookSpec } from './hook.spec.js';
import { integratedApiSpec } from './integrated-api.spec.js';
import { jsonSchemaValidatorSpec } from './json-schema-validator.spec.js';
import { personBatchJobSpec } from './person-batch-job.spec.js';
import { personJobSpec } from './person-job.spec.js';
import { startSpec } from './start.spec.js';
import { subDiagramSpec } from './sub-diagram.spec.js';
import { templateJobSpec } from './template-job.spec.js';
import { typescriptAstSpec } from './typescript-ast.spec.js';
import { userResponseSpec } from './user-response.spec.js';

export { 
  apiJobSpec,
  codeJobSpec,
  conditionSpec,
  dbSpec,
  endpointSpec,
  hookSpec,
  integratedApiSpec,
  jsonSchemaValidatorSpec,
  personBatchJobSpec,
  personJobSpec,
  startSpec,
  subDiagramSpec,
  templateJobSpec,
  typescriptAstSpec,
  userResponseSpec
};

export const nodeSpecificationRegistry: NodeSpecificationRegistry = {
  api_job: apiJobSpec,
  code_job: codeJobSpec,
  condition: conditionSpec,
  db: dbSpec,
  endpoint: endpointSpec,
  hook: hookSpec,
  integrated_api: integratedApiSpec,
  json_schema_validator: jsonSchemaValidatorSpec,
  person_batch_job: personBatchJobSpec,
  person_job: personJobSpec,
  start: startSpec,
  sub_diagram: subDiagramSpec,
  template_job: templateJobSpec,
  typescript_ast: typescriptAstSpec,
  user_response: userResponseSpec
};