name: Build Windows Installer

on:
  push:
    branches: [ main, dev ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '0.1.0'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './apps/desktop/src-tauri -> target'
      
      - name: Install Windows dependencies
        run: |
          # Install Visual Studio Build Tools components if needed
          # This is usually pre-installed on GitHub Actions Windows runners
      
      - name: Generate icons
        working-directory: apps/desktop
        run: |
          # Create a simple icon if not exists (for CI purposes)
          if (!(Test-Path "src-tauri/icons/icon.png")) {
            # Create icons directory
            New-Item -ItemType Directory -Force -Path "src-tauri/icons"
            
            # Download a placeholder icon or generate one
            # For now, we'll skip this step and assume icons are committed
          }
      
      - name: Build Python Backend
        working-directory: apps/server
        run: |
          # Create virtual environment
          python -m venv .venv
          
          # Activate and install dependencies
          & ".\.venv\Scripts\Activate.ps1"
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller
          
          # Install DiPeO packages in editable mode
          pip install -e "${{ github.workspace }}"
          pip install -e .
          
          # Build executable
          pyinstaller build.spec --clean --noconfirm
          
          # Verify executable was created
          if (!(Test-Path "dist/dipeo-server.exe")) {
            Write-Error "Backend build failed"
            exit 1
          }
          
          Write-Host "Backend build complete: $(Get-Item dist/dipeo-server.exe).Length bytes"
      
      - name: Build CLI Tool
        working-directory: apps/cli
        run: |
          # Create virtual environment
          python -m venv .venv
          
          # Activate and install dependencies
          & ".\.venv\Scripts\Activate.ps1"
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller
          
          # Install DiPeO core package in editable mode
          pip install -e "${{ github.workspace }}"
          pip install -e .
          
          # Build CLI executable
          pyinstaller --onefile --name dipeo --distpath dist src/dipeo_cli/minimal_cli.py
          
          # Verify executable was created
          if (!(Test-Path "dist/dipeo.exe")) {
            Write-Error "CLI build failed"
            exit 1
          }
          
          Write-Host "CLI build complete: $(Get-Item dist/dipeo.exe).Length bytes"
      
      - name: Install all dependencies
        run: |
          pnpm install --frozen-lockfile
      
      - name: Build Frontend
        working-directory: apps/web
        run: |
          pnpm build
          
          # Verify build output
          if (!(Test-Path "dist/index.html")) {
            Write-Error "Frontend build failed"
            exit 1
          }

      
      - name: Build Tauri Application
        working-directory: apps/desktop
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          # Verify backend and CLI executables exist
          if (!(Test-Path "${{ github.workspace }}/apps/server/dist/dipeo-server.exe")) {
            Write-Error "Backend executable not found"
            exit 1
          }
          
          if (!(Test-Path "${{ github.workspace }}/apps/cli/dist/dipeo.exe")) {
            Write-Error "CLI executable not found"
            exit 1
          }
          
          # Build Tauri application
          pnpm tauri build --target x86_64-pc-windows-msvc
      
      - name: Prepare artifacts
        run: |
          # Create output directory
          New-Item -ItemType Directory -Force -Path "./dist"
          
          # Find and copy installers
          $version = "${{ github.event.inputs.version || '0.1.0' }}"
          
          # Find installer (could be in nsis or other bundle directories)
          $installerPath = Get-ChildItem -Path "apps/desktop/src-tauri/target/release/bundle" -Recurse -Include "*.msi", "*.exe" | 
                           Where-Object { $_.Name -like "*setup*" -or $_.Name -like "*installer*" -or $_.Directory.Name -eq "nsis" } | 
                           Select-Object -First 1
          
          if ($installerPath) {
            $outputFile = "./dist/DiPeO-Setup-$version-x64$($installerPath.Extension)"
            Copy-Item -Path $installerPath.FullName -Destination $outputFile
            Write-Host "Installer copied to: $outputFile"
          }
          
          # Copy MSI installer separately if exists
          $msiInstaller = Get-ChildItem -Path "apps/desktop/src-tauri/target/release/bundle/msi" -Filter "*.msi" | Select-Object -First 1
          if ($msiInstaller) {
            Copy-Item $msiInstaller.FullName -Destination "./dist/DiPeO-$version-x64.msi"
          }
          
          # Copy CLI executable
          Copy-Item -Path "apps/cli/dist/dipeo.exe" -Destination "./dist/dipeo.exe"
          Write-Host "CLI executable copied to: ./dist/dipeo.exe"
          
          # List artifacts
          Get-ChildItem -Path "./dist"
      
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: dipeo-windows-installer
          path: dist/DiPeO-Setup-*
          retention-days: 30
      
      - name: Upload MSI Installer
        uses: actions/upload-artifact@v4
        with:
          name: dipeo-windows-msi
          path: dist/DiPeO-*.msi
          retention-days: 30
      
      - name: Upload CLI Executable
        uses: actions/upload-artifact@v4
        with:
          name: dipeo-cli-windows
          path: dist/dipeo.exe
          retention-days: 30
      
      - name: Create Release (if tagged)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: |
            dist/DiPeO-Setup-*.exe
            dist/DiPeO-*.msi
          body: |
            # DiPeO ${{ github.ref_name }}
            
            ## Downloads
            - 🪟 **Windows Installer (Recommended):** `DiPeO-Setup-${{ github.ref_name }}-x64.exe`
            - 📦 **Windows MSI:** `DiPeO-${{ github.ref_name }}-x64.msi`
            
            ## Installation
            1. Download the installer for your platform
            2. Run the installer (you may need to click "More info" → "Run anyway" if you see a SmartScreen warning)
            3. Follow the installation wizard
            4. Launch DiPeO from the Start Menu or Desktop shortcut
            
            ## System Requirements
            - Windows 10 or later (64-bit)
            - 4GB RAM minimum (8GB recommended)
            - 200MB free disk space
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}